/* Camping Paradis — dictionnaire EN
   Cle: texte francais exact (espaces normalises). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['en'] = {
  "Installer l'application": "Install the app",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Access all the campsite info in one click, even offline!",
  "Appuie sur le bouton": "Tap the button",
  "Partager": "Share",
  "⬆️ en bas de Safari": "⬆️ at the bottom of Safari",
  "Sélectionne": "Select",
  "\"Sur l'écran d'accueil\"": "\"Add to Home Screen\"",
  "Appuie sur": "Tap",
  "\"Ajouter\"": "\"Add\"",
  "en haut à droite": "at the top right",
  "Appuie sur le menu": "Tap the menu",
  "\"Ajouter à l'écran d'accueil\"": "\"Add to Home screen\"",
  "Confirme en appuyant sur": "Confirm by tapping",
  "✓ J'ai compris !": "✓ Got it!",
  "Continuer sans installer": "Continue without installing",
  "📱 Installer l'App": "📱 Install the App",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Today",
  "Aujourd'hui": "Today",
  "Chargement...": "Loading...",
  "Voir plus →": "See more →",
  "Bon plan du moment": "Today's special deal",
  "Météo indisponible": "Weather unavailable",
  "Ciel dégagé": "Clear sky",
  "Principalement dégagé": "Mostly clear",
  "Partiellement nuageux": "Partly cloudy",
  "Couvert": "Overcast",
  "Brouillard": "Fog",
  "Brouillard givrant": "Freezing fog",
  "Bruine légère": "Light drizzle",
  "Bruine modérée": "Moderate drizzle",
  "Bruine dense": "Dense drizzle",
  "Pluie légère": "Light rain",
  "Pluie modérée": "Moderate rain",
  "Pluie forte": "Heavy rain",
  "Averses légères": "Light showers",
  "Averses modérées": "Moderate showers",
  "Averses fortes": "Heavy showers",
  "Neige légère": "Light snow",
  "Neige modérée": "Moderate snow",
  "Neige forte": "Heavy snow",
  "Averses de neige": "Snow showers",
  "Averses de neige fortes": "Heavy snow showers",
  "Orage": "Thunderstorm",
  "Orage avec grêle": "Thunderstorm with hail",
  "Orage violent": "Severe thunderstorm",
  "Variable": "Changeable",
  "Vie au camping": "Campsite life",
  "Horaires du Camping": "Campsite opening hours",
  "Réception, piscine, animations et services": "Reception, pool, entertainment and services",
  "Plan du camping": "Campsite map",
  "Retrouvez votre emplacement et les équipements": "Find your pitch and the facilities",
  "Tout savoir pour votre arrivée et départ": "Everything you need to know for arrival and departure",
  "Pot d'accueil": "Welcome drink",
  "Rejoignez-nous pour un verre de bienvenue": "Join us for a welcome drink",
  "Service optionnel": "Optional service",
  "Ménage fin de séjour": "End-of-stay cleaning",
  "Partez l'esprit libre — on s'occupe de tout": "Leave worry-free — we take care of everything",
  "Service disponible sur demande": "Service available on request",
  "Tarifs forfaitaires": "Flat rates",
  "Mobil-home 2 ch.": "2-bedroom mobile home",
  "Mobil-home 3 ch.": "3-bedroom mobile home",
  "Inclus dans la prestation": "Included in the service",
  "Nettoyage complet du logement": "Full cleaning of the accommodation",
  "Sanitaires et cuisine": "Bathroom and kitchen",
  "Gestion des déchets": "Waste disposal",
  "Confirmation par la réception": "Confirmation by reception",
  "N° d'emplacement *": "Pitch number *",
  "Date de départ *": "Departure date *",
  "Téléphone (optionnel)": "Phone (optional)",
  "Demander le ménage →": "Request cleaning →",
  "Annuler": "Cancel",
  "Demande envoyée !": "Request sent!",
  "Notre équipe a bien reçu votre demande.": "Our team has received your request.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "We will confirm the exact price for your pitch.",
  "Fermer": "Close",
  "Nos Services": "Our Services",
  "Kayak": "Kayaking",
  "Explorez le lac du Val d'Oignin en kayak": "Explore Lake Val d'Oignin by kayak",
  "Laverie": "Laundry",
  "Service de laverie disponible 24h/24": "Laundry service available 24/7",
  "Locations Diverses": "Equipment rental",
  "Locations diverses": "Equipment rental",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbecue, bed linen, baby kit, towels",
  "Connexion internet gratuite": "Free internet access",
  "Restauration & Bar": "Food & Bar",
  "Burgers, salades et plats du jour": "Burgers, salads and daily specials",
  "Cocktails, bières et boissons fraîches": "Cocktails, beers and cold drinks",
  "Épicerie": "Grocery shop",
  "Produits essentiels": "Everyday essentials",
  "Petit-Déjeuner": "Breakfast",
  "Petit-déjeuner": "Breakfast",
  "Pain frais et viennoiseries chaque matin": "Fresh bread and pastries every morning",
  "Autour du camping": "Around the campsite",
  "Activités à faire": "Things to do",
  "Kayak, randonnées, sports et loisirs en plein air": "Kayaking, hiking, sports and outdoor leisure",
  "Restaurants": "Restaurants",
  "Les meilleures tables autour du camping": "The best restaurants near the campsite",
  "À visiter": "Places to visit",
  "Gorges de l'Ain, viaduc, cascade et villages": "Ain gorges, viaduct, waterfall and villages",
  "Randonnées et Balades": "Hikes and Walks",
  "Sentiers balisés pour tous les niveaux": "Marked trails for all levels",
  "Marchés": "Markets",
  "Producteurs locaux et marchés de la région": "Local producers and regional markets",
  "Commerces": "Shops",
  "Supermarchés et commerces à proximité": "Supermarkets and shops nearby",
  "Animations": "Entertainment",
  "Programme de la semaine": "This week's programme",
  "Activités, soirées et événements à ne pas manquer": "Activities, evenings and events not to be missed",
  "Club enfants": "Kids' club",
  "Ateliers et aventures pour les 6-12 ans": "Workshops and adventures for ages 6–12",
  "Montez sur scène et brillez devant tout le camping !": "Get on stage and shine in front of the whole campsite!",
  "Circulation": "Getting around",
  "Horaires de la barrière": "Barrier opening hours",
  "Entrées et sorties du camping : plages horaires": "Campsite entry and exit times",
  "Véhicule électrique": "Electric vehicle",
  "Recharge disponible sur site — infos et tarifs": "Charging available on site — info and prices",
  "Signaler un problème": "Report a problem",
  "Notre équipe intervient dans les plus brefs délais.": "Our team will respond as quickly as possible.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Describe your situation and we will get back to you quickly.",
  "Type de problème *": "Type of problem *",
  "Choisir...": "Choose...",
  "🚿 Sanitaires": "🚿 Sanitary facilities",
  "🔌 Électricité / Eau": "🔌 Electricity / Water",
  "🔊 Nuisances sonores": "🔊 Noise nuisance",
  "🗑️ Propreté": "🗑️ Cleanliness",
  "🌿 Végétation / Terrain": "🌿 Vegetation / Grounds",
  "🚗 Circulation / Barrière": "🚗 Traffic / Barrier",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurant / Shop",
  "🏊 Piscine": "🏊 Pool",
  "❓ Autre": "❓ Other",
  "Description *": "Description *",
  "Envoyer le signalement →": "Send report →",
  "Signalement envoyé !": "Report sent!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Our team has received your message and will respond as soon as possible.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Thank you for helping us improve your stay 🙏",
  "© 2026 Tous droits réservés.": "© 2026 All rights reserved.",
  "Assistant Camping": "Campsite Assistant",
  "Réponses immédiates": "Instant answers",
  "Réception": "Reception",
  "Voir les horaires": "See opening hours",
  "Passer en mode sombre": "Switch to dark mode",
  "Passer en mode clair": "Switch to light mode",
  "Appeler la réception": "Call reception",
  "Changer le thème": "Change theme",
  "Effacer": "Clear",
  "Envoyer": "Send",
  "Ouvrir l'assistant": "Open the assistant",
  "Rechercher dans l'application": "Search the app",
  "Décrivez votre problème en quelques mots...": "Describe your problem in a few words...",
  "Ex : 42": "E.g. 42",
  "Pour confirmation": "For confirmation",
  "Pour qu'on vous rappelle si besoin": "So we can call you back if needed",
  "Rechercher une page, un service, une activité…": "Search for a page, service or activity…",
  "Écrivez votre question…": "Type your question…",
  "Numéro uniquement": "Numbers only",
  "Supermarchés": "Supermarkets",
  "Santé": "Health",
  "Petits Commerces": "Local shops",
  "Grandes surfaces et courses du quotidien": "Supermarkets and everyday shopping",
  "Pharmacie, médecins et urgences": "Pharmacy, doctors and emergencies",
  "Boulangerie, tabac et presse à Izernore": "Bakery, tobacconist and newsagent in Izernore",
  "← Toutes les catégories": "← All categories",
  "Adresse": "Address",
  "Horaires": "Opening hours",
  "Téléphone": "Phone",
  "Site web": "Website",
  "💡 Pour le dépannage, pensez aussi à": "💡 For quick top-up shopping, don't forget",
  "l'épicerie du camping": "the campsite grocery shop",
  "Supermarché complet avec rayon boulangerie, le plus pratique pour les grosses courses.": "Full supermarket with a bakery section, the most convenient for big shopping trips.",
  "Pratique au retour du lac de Nantua. Espace dédié aux camping-cars à côté du magasin.": "Convenient on the way back from Lake Nantua. Dedicated motorhome area next to the shop.",
  "Le plus grand choix de la région (hypermarché), avec station-service.": "The widest choice in the area (hypermarket), with a petrol station.",
  "Enseigne discount bien connue de nos vacanciers européens.": "A discount chain well known to our European guests.",
  "La pharmacie la plus proche du camping. Équipe accueillante et de bon conseil.": "The closest pharmacy to the campsite. Friendly and helpful team.",
  "Maison de santé regroupant médecins généralistes et autres praticiens.": "Health centre with general practitioners and other practitioners.",
  "Le service d'urgences le plus proche du camping.": "The closest emergency department to the campsite.",
  "Numéros d'urgence :": "Emergency numbers:",
  "15 (SAMU) · 112 (urgences européennes) · 3237 (pharmacie de garde)": "15 (SAMU ambulance) · 112 (European emergency number) · 3237 (on-duty pharmacy)",
  "En cas de besoin, la réception du camping est là pour vous aider :": "If you need help, the campsite reception is here for you:",
  "🥐 Pain frais et viennoiseries disponibles chaque matin": "🥐 Fresh bread and pastries available every morning",
  "au camping": "at the campsite",
  "Boulangerie artisanale : pains, pâtisseries et petit salon de thé avec terrasse.": "Artisan bakery: breads, pastries and a small tea room with terrace.",
  "Tabac, presse, jeux, souvenirs et petit dépannage alimentaire.": "Tobacconist, newsagent, games, souvenirs and basic groceries.",
  "Lun–Sam : 8h30–19h30 · Dim : 9h–12h30": "Mon–Sat: 8:30am–7:30pm · Sun: 9am–12:30pm",
  "Lun–Sam : 8h30–20h · Dim : 8h30–12h30": "Mon–Sat: 8:30am–8pm · Sun: 8:30am–12:30pm",
  "Lun–Sam : 8h–20h · Dim : 8h–12h15": "Mon–Sat: 8am–8pm · Sun: 8am–12:15pm",
  "Lun–Ven : 8h45–12h15 / 14h45–19h · Sam : 8h45–12h30": "Mon–Fri: 8:45am–12:15pm / 2:45–7pm · Sat: 8:45am–12:30pm",
  "Lun–Ven : 8h–18h": "Mon–Fri: 8am–6pm",
  "Lun, Mar, Jeu–Sam : 6h–19h · Dim : 6h–13h · Fermé le mercredi": "Mon, Tue, Thu–Sat: 6am–7pm · Sun: 6am–1pm · Closed on Wednesdays",
  "Lun–Sam : 6h30–12h30 / 15h–19h · Dim : 7h–12h30": "Mon–Sat: 6:30am–12:30pm / 3–7pm · Sun: 7am–12:30pm"
};

/* ── Horaires ── */
window.CP_I18N['en'] = Object.assign(window.CP_I18N['en'], {
  "Horaires": "Opening hours",
  "Réception": "Reception",
  "Snack": "Snack bar",
  "Bar": "Bar",
  "Espace Aquatique": "Swimming area",
  "Notre équipe est à votre disposition à l'accueil pour répondre à toutes vos questions !": "Our team is available at reception to answer all your questions!",
  "Basse Saison (Mai, Juin, Septembre)": "Low season (May, June, September)",
  "Haute Saison (Juillet - Août)": "High season (July - August)",
  "Dimanche - Vendredi": "Sunday - Friday",
  "Samedi": "Saturday",
  "Lundi - Vendredi": "Monday - Friday",
  "Samedi & Dimanche": "Saturday & Sunday",
  "Services :": "Services:",
  "Planche de charcuteries et de fromages locales | Commande à la carte du bar/snack sans réservation | Soirée à thème sur réservation (uniquement en juillet/août)": "Local charcuterie and cheese board | À la carte bar/snack orders without reservation | Themed evenings by reservation (July/August only)",
  "Du 15 mai au 15 septembre 2026": "From 15 May to 15 September 2026",
  "Cocktails à la carte | Boissons alcoolisées, soft, bières, vins | Vente de glaces | Dépôt de pain à partir de 8h00": "À la carte cocktails | Alcoholic drinks, soft drinks, beers, wines | Ice cream sales | Bread available from 8:00am",
  "Pain & Viennoiseries :": "Bread & Pastries:",
  "Commande au plus tard la veille avant 18h pour le lendemain": "Order by 6pm the day before for the next morning",
  "Baignade surveillée l'après-midi uniquement en haute saison.": "Supervised swimming in the afternoon only during high season.",
  "Horaires :": "Opening hours:",
  "De 10h00 à 19h00": "From 10:00am to 7:00pm",
  "Prix :": "Price:",
  "Gratuit pour la clientèle du camping": "Free for campsite guests",
  "Règles d'accès :": "Access rules:",
  "- Bracelets obligatoires": "- Wristbands required",
  "- Short de bain interdit": "- Board shorts not allowed",
  "- Chaussures à laisser à l'entrée avant le pédiluve": "- Leave shoes at the entrance before the foot bath",
  "- Tongs autorisées": "- Flip-flops allowed",
  "Info :": "Info:",
  "Messieurs, vous avez oublié votre maillot de bain ? On en vend à la réception à 15€.": "Gentlemen, forgotten your swimming trunks? We sell them at reception for €15.",
  "Du 23 mai au 15 septembre 2026": "From 23 May to 15 September 2026",
  "Ouverture : 30/04/2026 au 28/09/2026": "Open: 30/04/2026 to 28/09/2026"
});

/* ── Toutes pages ── */
window.CP_I18N['en'] = Object.assign(window.CP_I18N['en'], {
  "Activités de Plein Air": "Outdoor Activities",
  "Activités Nautiques": "Water Activities",
  "Activités Intérieur": "Indoor Activities",
  "Activités nautiques": "Water activities",
  "Activités disponibles selon la saison": "Activities available depending on the season",
  "Activités familiales et pour enfants": "Family and children activities",
  "Avec ou sans réservation": "With or without reservation",
  "Consultez la réception pour les détails": "Check with reception for details",
  "Toute l'année": "All year round",
  "Tous les âges": "All ages",
  "Informations": "Information",
  "Plein Air": "Outdoors",
  "Nautiques": "Water",
  "Intérieur": "Indoor",
  "Baignade": "Swimming",
  "Pédalo": "Pedalo",
  "Canoë, Paddle": "Canoe, Paddle",
  "Canyoning": "Canyoning",
  "Randonnées dans le Jura": "Hikes in the Jura",
  "Randonnées dans l'Ain": "Hikes in the Ain",
  "Randonnées - Jura": "Hikes - Jura",
  "Randonnées et balades": "Hikes and walks",
  "Balade équestre": "Horse riding",
  "Ouverture": "Opening hours",
  "Ouvert à l'année": "Open all year",
  "Ouvert 24/7": "Open 24/7",
  "Ouvert 7j/7 24h/24": "Open 7 days a week, 24 hours a day",
  "Ouverture possible sur réservation": "Opening possible on reservation",
  "Conseils": "Tips",
  "Conseil :": "Tip:",
  "Bon plan :": "Good to know:",
  "Bon à savoir": "Good to know",
  "Astuce :": "Tip:",
  "Indications :": "Directions:",
  "Période d'ouverture": "Opening period",
  "Retour départ": "Returns to start",
  "Point haut": "Highest point",
  "Point bas": "Lowest point",
  "Dénivelé +": "Elevation gain",
  "Dénivelé -": "Elevation loss",
  "Distance": "Distance",
  "Durée": "Duration",
  "Facile": "Easy",
  "Moyenne": "Moderate",
  "Difficile": "Hard",
  "Kayak 1 place": "Single kayak",
  "Kayak 2 places": "Double kayak",
  "Paddle": "Paddleboard",
  "Gilet obligatoire": "Life jacket required",
  "Rangement inclus": "Storage included",
  "Libre service": "Self-service",
  "Payez seul !": "Pay on your own!",
  "Code par SMS": "Code by SMS",
  "Pour votre sécurité": "For your safety",
  "Accès libre": "Free access",
  "Découvrir Kayakomat": "Discover Kayakomat",
  "LOCATION DE KAYAK ET DE PADDLE EN LIBRE-SERVICE": "SELF-SERVICE KAYAK AND PADDLEBOARD RENTAL",
  "Réservez en ligne et ayez la liberté de payer où vous le souhaitez, quand vous souhaitez.": "Book online and pay wherever and whenever you want.",
  "La station de kayak et de paddle est en bas du camping (juste devant le lac). Si vous rencontrez un problème lors de la location, contactez-nous !": "The kayak and paddleboard station is at the bottom of the campsite (right in front of the lake). If you have any issue with your rental, contact us!",
  "Prix": "Prices",
  "Voir le site internet pour les tarifs": "See website for prices",
  "Voir le site internet pour les autres tarifs": "See website for other prices",
  "Voir site internet": "See website",
  "Tarifs à consulter auprès de l'organisateur": "Prices available from the organiser",
  "Tarif réduit": "Reduced rate",
  "Réservation": "Reservation",
  "Réservation obligatoire. Ne nécessite aucune préparation ni aptitude particulière.": "Booking required. No special preparation or fitness needed.",
  "Localisation": "Location",
  "Trajet": "Travel time",
  "Environ 15 minutes en voiture": "About 15 minutes by car",
  "Environ 15 minutes du camping en voiture": "About 15 minutes from the campsite by car",
  "Environ 20 minutes du camping en voiture": "About 20 minutes from the campsite by car",
  "Environ 25 minutes du camping en voiture": "About 25 minutes from the campsite by car",
  "Environ 45 minutes du camping en voiture": "About 45 minutes from the campsite by car",
  "Recharge à 15 minutes du Camping": "Charging 15 minutes from the campsite",
  "Oyonnax — à 15 minutes du camping": "Oyonnax — 15 minutes from the campsite",
  "Recharge disponible aux alentours du camping": "Charging available near the campsite",
  "Barrière": "Barrier",
  "Accès au camping": "Campsite access",
  "Vitesse de circulation": "Speed limit",
  "La barrière est ouverte de 8h00 à 23h00 tous les jours. Pour entrer dans le camping, utilisez le code indiqué sur votre enveloppe d'accueil. En cas d'arrivée nocturne (fermeture de la barrière) : Vous pouvez stationner votre voiture sur le parking visiteurs devant le camping et rejoindre votre emplacement à pied.": "The barrier is open from 8am to 11pm every day. To enter the campsite, use the code on your welcome envelope. If you arrive at night (barrier closed): you can park in the visitor car park in front of the campsite and walk to your pitch.",
  "La vitesse maximale autorisée dans le camping est de 10 km/h. Nous vous prions de bien vouloir respecter cette vitesse de circulation pour le respect de tout le monde et éviter tous risque d'accident.": "The maximum speed allowed on the campsite is 10 km/h. Please respect this limit for everyone's safety.",
  "Heure limite de départ": "Check-out time",
  "Remise des clés": "Key return",
  "À la réception — ou boite en bois à l'entrée du camping si départ avant 9h00": "At reception — or in the wooden box at the campsite entrance if leaving before 9am",
  "Procédure d'arrivée : check-in": "Arrival procedure: check-in",
  "Procédure de sortie : check-out": "Departure procedure: check-out",
  "Bienvenue au Camping Paradis Les Gorges du Haut-Bugey": "Welcome to Camping Paradis Les Gorges du Haut-Bugey",
  "Ça y est, les vacances peuvent commencer !": "The holidays can begin!",
  "Dans cette enveloppe, vous trouverez :": "In this envelope you will find:",
  "Une fiche de bienvenue": "A welcome form",
  "Le plan du camping pour mieux vous repérer.": "The campsite map to help you find your way around.",
  "Les bracelets du camping à porter tout le long de votre séjour": "Campsite wristbands to wear throughout your stay",
  "Code de la barrière": "Barrier code",
  "Vider les poubelles": "Empty the bins",
  "Faire la vaisselle": "Do the washing-up",
  "Remise des clés :": "Key return:",
  "Vous avez souscrit au forfait ménage, nous vous demandons seulement de :*": "If you have opted for the cleaning package, we only ask you to:*",
  "Vous n'avez pas souscrit au forfait ménage :": "If you have not opted for the cleaning package:",
  "Nous vous demandons de rendre l'hébergement aussi propre qu'il vous a été donné.": "Please leave the accommodation as clean as you found it.",
  "Votre semaine de vacances touche à sa fin et nous sommes aussi triste de vous voir partir.": "Your holiday is coming to an end and we're sad to see you go.",
  "Au programme :": "On the programme:",
  "Présentation de l'équipe du camping": "Introduction to the campsite team",
  "Planning des animations de la semaine": "Weekly entertainment schedule",
  "Bons plans et informations touristiques de la région": "Local tips and tourist information",
  "Verre de bienvenue offert": "Complimentary welcome drink",
  "Les dimanches à 19h.": "Sundays at 7pm.",
  "Juillet et août uniquement": "July and August only",
  "Espace animation du camping": "Campsite entertainment area",
  "Période": "Period",
  "Un mini-club pour vos enfants": "A kids' club for your children",
  "Les enfants ne s'ennuieront pas : jeux, animations, mini-disco, activités… les journées sont bien remplies !": "The children won't be bored: games, entertainment, mini-disco, activities… the days are packed!",
  "Ils prendront plaisir à participer aux nombreuses activités du Piki Club (6-12 ans).": "They'll love taking part in the many activities of the Piki Club (ages 6–12).",
  "De 9h30 à 12h et de 15h30 à 18h du 6 juillet au 31 août": "From 9:30am to 12pm and 3:30pm to 6pm, 6 July to 31 August",
  "Gratuit, inclus dans la réservation": "Free, included in your booking",
  "Inscription obligatoire auprès de l'équipe d'animation lors du pot d'accueil le dimanche à 19h00.": "Registration required with the entertainment team at the Sunday welcome drink at 7pm.",
  "Juillet et août": "July and August",
  "Retrouvez facilement votre emplacement, les sanitaires, la piscine, le snack-bar et tous les équipements du camping grâce au plan ci-dessous. Zoomez pour voir les numéros d'emplacements en détail.": "Easily find your pitch, the sanitary facilities, the pool, the snack bar and all campsite amenities on the map below. Zoom in to see pitch numbers in detail.",
  "Besoin d'aide pour vous repérer ?": "Need help finding your way?",
  "N'hésitez pas à passer à la réception, notre équipe vous indiquera le chemin avec plaisir !": "Don't hesitate to stop by reception — our team will be happy to show you the way!",
  "Pincez l'écran pour zoomer sur le programme.": "Pinch the screen to zoom in on the programme.",
  "Astuce :": "Tip:",
  "Sauvegarder le programme": "Save the programme",
  "WiFi Gratuit": "Free WiFi",
  "Connexion internet gratuite et rapide partout dans le camping.": "Fast, free internet connection throughout the campsite.",
  "Restez connectés avec famille et amis durant votre séjour en pleine nature.": "Stay connected with family and friends during your nature stay.",
  "Réseau": "Network",
  "Camping-Paradis-WiFi": "Camping-Paradis-WiFi",
  "Tarif": "Rate",
  "Gratuit pour tous les clients": "Free for all guests",
  "Disponibilité": "Availability",
  "Couverture": "Coverage",
  "Uniquement autour de la réception": "Only around the reception area",
  "Code d'accès": "Access code",
  "Pas de mot de passe, accès direct": "No password required, direct access",
  "Vitesse": "Speed",
  "Haut débit": "High speed",
  "Support": "Support",
  "Contactez la réception en cas de souci": "Contact reception if you have any issues",
  "Service de Laverie": "Laundry service",
  "Vous trouverez des machines à laver au sanitaire principal.": "You will find washing machines in the main sanitary block.",
  "La laverie est composée de deux machines à laver et d'un sèche-linge. Elle est ouverte 24h/24 pendant toute la saison.": "The laundry has two washing machines and a dryer. It is open 24 hours a day throughout the season.",
  "Application WASHIN": "WASHIN app",
  "Disponible sur Apple et Android": "Available on Apple and Android",
  "Paiement direct": "Direct payment",
  "Sur les machines disponibles": "On the available machines",
  "Avantage :": "Advantage:",
  "Alimentation générale": "General groceries",
  "Produits de base et articles courants (riz, pâtes, confiture, pain de mie, gel douche, dentifrice, brosse à dent ...)": "Basic products and everyday items (rice, pasta, jam, sandwich bread, shower gel, toothpaste, toothbrush...)",
  "Horaires à consulter à la réception": "Opening hours available at reception",
  "Baguettes": "Baguettes",
  "Viennoiseries": "Pastries",
  "Pain frais du jour": "Fresh bread of the day",
  "Croissants et pains au chocolat": "Croissants and pain au chocolat",
  "Commande": "Order",
  "Délai de commande": "Order deadline",
  "Avant 18h la veille pour le lendemain": "Before 6pm the day before",
  "Retrait": "Collection",
  "Directement au bar/snack du camping le matin": "Directly at the campsite snack bar in the morning",
  "Au bar/snack du camping": "At the campsite snack bar",
  "HORAIRES BAR / SNACK": "BAR / SNACK OPENING HOURS",
  "CARTE BAR / SNACK": "BAR / SNACK MENU",
  "Notre bar": "Our bar",
  "Notre bar est à votre disposition pour partager un verre en famille, entre amis et faire de nouvelles rencontres.": "Our bar is at your disposal to share a drink with family, friends and make new acquaintances.",
  "Cocktails maisons & bières de la région": "House cocktails & local beers",
  "Venez déguster nos délicieux cocktails maisons et bières de la région !": "Come and taste our delicious house cocktails and local beers!",
  "Du 15 mai au 15 septembre 2026": "From 15 May to 15 September 2026",
  "Tous les jours sauf le mercredi — du 15 mai au 15 septembre 2026": "Every day except Wednesday — from 15 May to 15 September 2026",
  "À la carte": "À la carte",
  "Sans réservation, sauf pour les soirées à thème": "No reservation needed, except for themed evenings",
  "Soirée moules frites — tous les vendredi": "Mussels and fries evening — every Friday",
  "Soirée paëlla — tous les dimanches": "Paella evening — every Sunday",
  "Soirée barbecue + frites à volonté — tous les jeudis": "Barbecue + unlimited fries — every Thursday",
  "À partir de 19h00": "From 7pm",
  "À partir de 20h30": "From 8:30pm",
  "Spectacles & concerts en haute saison": "Shows & concerts in high season",
  "Pêcher dans le Haut-Bugey": "Fishing in the Haut-Bugey",
  "Escalade, accrobranche et via ferrata": "Climbing, tree climbing and via ferrata",
  "Domaine équestre de la maurinière": "Domaine équestre de la Maurinière",
  "Partez à la découverte des paysages du Haut-Bugey : gorges, forêts, lacs et villages à explorer à pied ou à vélo !": "Discover the landscapes of the Haut-Bugey: gorges, forests, lakes and villages to explore on foot or by bike!",
  "Supermarchés": "Supermarkets",
  "Santé": "Health",
  "Petits Commerces": "Local shops",
  "Découvrez toutes les activités disponibles près du camping pour profiter au maximum de votre séjour !": "Discover all the activities available near the campsite to make the most of your stay!",
  "Nous sommes ravis de vous inviter à un pot d'accueil le dimanche à 19h (en juillet/août). Cela sera l'occasion de faire connaissance, de vous présenter l'équipe, le planning d'animation et les informations touristiques de la région.": "We are delighted to invite you to a welcome drink on Sunday at 7pm (July/August). It's a chance to get to know each other, meet the team, discover the weekly entertainment schedule and learn about the region."
});
