/* Camping Paradis — dictionnaire ES
   Cle: texte francais exact (espaces normalises). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['es'] = {
  "Installer l'application": "Instalar la aplicación",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Accede a toda la información del camping con un clic, ¡incluso sin conexión!",
  "Appuie sur le bouton": "Pulsa el botón",
  "Partager": "Compartir",
  "⬆️ en bas de Safari": "⬆️ abajo en Safari",
  "Sélectionne": "Selecciona",
  "\"Sur l'écran d'accueil\"": "\"Añadir a pantalla de inicio\"",
  "Appuie sur": "Pulsa",
  "\"Ajouter\"": "\"Añadir\"",
  "en haut à droite": "arriba a la derecha",
  "Appuie sur le menu": "Pulsa el menú",
  "\"Ajouter à l'écran d'accueil\"": "\"Añadir a pantalla de inicio\"",
  "Confirme en appuyant sur": "Confirma pulsando",
  "✓ J'ai compris !": "✓ ¡Entendido!",
  "Continuer sans installer": "Continuar sin instalar",
  "📱 Installer l'App": "📱 Instalar la App",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Hoy",
  "Aujourd'hui": "Hoy",
  "Chargement...": "Cargando...",
  "Voir plus →": "Ver más →",
  "Bon plan du moment": "Oferta del momento",
  "Météo indisponible": "Tiempo no disponible",
  "Ciel dégagé": "Cielo despejado",
  "Principalement dégagé": "Mayormente despejado",
  "Partiellement nuageux": "Parcialmente nublado",
  "Couvert": "Cubierto",
  "Brouillard": "Niebla",
  "Brouillard givrant": "Niebla helada",
  "Bruine légère": "Llovizna ligera",
  "Bruine modérée": "Llovizna moderada",
  "Bruine dense": "Llovizna densa",
  "Pluie légère": "Lluvia ligera",
  "Pluie modérée": "Lluvia moderada",
  "Pluie forte": "Lluvia fuerte",
  "Averses légères": "Chubascos ligeros",
  "Averses modérées": "Chubascos moderados",
  "Averses fortes": "Chubascos fuertes",
  "Neige légère": "Nieve ligera",
  "Neige modérée": "Nieve moderada",
  "Neige forte": "Nieve fuerte",
  "Averses de neige": "Chubascos de nieve",
  "Averses de neige fortes": "Chubascos de nieve fuertes",
  "Orage": "Tormenta",
  "Orage avec grêle": "Tormenta con granizo",
  "Orage violent": "Tormenta fuerte",
  "Variable": "Variable",
  "Vie au camping": "Vida en el camping",
  "Horaires du Camping": "Horarios del camping",
  "Réception, piscine, animations et services": "Recepción, piscina, animación y servicios",
  "Plan du camping": "Plano del camping",
  "Retrouvez votre emplacement et les équipements": "Encuentra tu parcela y las instalaciones",
  "Tout savoir pour votre arrivée et départ": "Todo sobre tu llegada y salida",
  "Pot d'accueil": "Copa de bienvenida",
  "Rejoignez-nous pour un verre de bienvenue": "Acompáñanos a tomar una copa de bienvenida",
  "Service optionnel": "Servicio opcional",
  "Ménage fin de séjour": "Limpieza de fin de estancia",
  "Partez l'esprit libre — on s'occupe de tout": "Márchate sin preocupaciones: nosotros nos encargamos de todo",
  "Service disponible sur demande": "Servicio disponible bajo petición",
  "Tarifs forfaitaires": "Tarifas fijas",
  "Mobil-home 2 ch.": "Mobil home 2 hab.",
  "Mobil-home 3 ch.": "Mobil home 3 hab.",
  "Inclus dans la prestation": "Incluido en el servicio",
  "Nettoyage complet du logement": "Limpieza completa del alojamiento",
  "Sanitaires et cuisine": "Baño y cocina",
  "Gestion des déchets": "Gestión de residuos",
  "Confirmation par la réception": "Confirmación por parte de la recepción",
  "N° d'emplacement *": "N.º de parcela *",
  "Date de départ *": "Fecha de salida *",
  "Téléphone (optionnel)": "Teléfono (opcional)",
  "Demander le ménage →": "Solicitar limpieza →",
  "Annuler": "Cancelar",
  "Demande envoyée !": "¡Solicitud enviada!",
  "Notre équipe a bien reçu votre demande.": "Nuestro equipo ha recibido tu solicitud.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "Te confirmaremos la tarifa exacta según tu parcela.",
  "Fermer": "Cerrar",
  "Nos Services": "Nuestros servicios",
  "Kayak": "Kayak",
  "Explorez le lac du Val d'Oignin en kayak": "Explora el lago de Val d'Oignin en kayak",
  "Laverie": "Lavandería",
  "Service de laverie disponible 24h/24": "Servicio de lavandería disponible 24 h",
  "Locations Diverses": "Alquileres",
  "Locations diverses": "Alquileres",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbacoa, sábanas, kit de bebé, toallas",
  "Connexion internet gratuite": "Conexión a internet gratuita",
  "Restauration & Bar": "Restauración y bar",
  "Burgers, salades et plats du jour": "Hamburguesas, ensaladas y platos del día",
  "Cocktails, bières et boissons fraîches": "Cócteles, cervezas y bebidas frías",
  "Épicerie": "Tienda",
  "Produits essentiels": "Productos básicos",
  "Petit-Déjeuner": "Desayuno",
  "Petit-déjeuner": "Desayuno",
  "Pain frais et viennoiseries chaque matin": "Pan fresco y bollería cada mañana",
  "Autour du camping": "Alrededores del camping",
  "Activités à faire": "Actividades",
  "Kayak, randonnées, sports et loisirs en plein air": "Kayak, senderismo, deportes y ocio al aire libre",
  "Restaurants": "Restaurantes",
  "Les meilleures tables autour du camping": "Los mejores restaurantes cerca del camping",
  "À visiter": "Lugares para visitar",
  "Gorges de l'Ain, viaduc, cascade et villages": "Gargantas del Ain, viaducto, cascada y pueblos",
  "Randonnées et Balades": "Senderismo y paseos",
  "Sentiers balisés pour tous les niveaux": "Senderos señalizados para todos los niveles",
  "Marchés": "Mercados",
  "Producteurs locaux et marchés de la région": "Productores locales y mercados de la región",
  "Commerces": "Comercios",
  "Supermarchés et commerces à proximité": "Supermercados y comercios cercanos",
  "Animations": "Animación",
  "Programme de la semaine": "Programa de la semana",
  "Activités, soirées et événements à ne pas manquer": "Actividades, veladas y eventos que no te puedes perder",
  "Club enfants": "Club infantil",
  "Ateliers et aventures pour les 6-12 ans": "Talleres y aventuras para niños de 6 a 12 años",
  "Montez sur scène et brillez devant tout le camping !": "¡Súbete al escenario y brilla ante todo el camping!",
  "Circulation": "Circulación",
  "Horaires de la barrière": "Horarios de la barrera",
  "Entrées et sorties du camping : plages horaires": "Entradas y salidas del camping: franjas horarias",
  "Véhicule électrique": "Vehículo eléctrico",
  "Recharge disponible sur site — infos et tarifs": "Recarga disponible en el camping: información y tarifas",
  "Signaler un problème": "Informar de un problema",
  "Notre équipe intervient dans les plus brefs délais.": "Nuestro equipo intervendrá lo antes posible.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Describe tu situación y te responderemos rápidamente.",
  "Type de problème *": "Tipo de problema *",
  "Choisir...": "Elegir...",
  "🚿 Sanitaires": "🚿 Sanitarios",
  "🔌 Électricité / Eau": "🔌 Electricidad / Agua",
  "🔊 Nuisances sonores": "🔊 Ruidos molestos",
  "🗑️ Propreté": "🗑️ Limpieza",
  "🌿 Végétation / Terrain": "🌿 Vegetación / Terreno",
  "🚗 Circulation / Barrière": "🚗 Circulación / Barrera",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurante / Tienda",
  "🏊 Piscine": "🏊 Piscina",
  "❓ Autre": "❓ Otro",
  "Description *": "Descripción *",
  "Envoyer le signalement →": "Enviar el aviso →",
  "Signalement envoyé !": "¡Aviso enviado!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Nuestro equipo ha recibido tu mensaje e intervendrá lo antes posible.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Gracias por ayudarnos a mejorar tu estancia 🙏",
  "© 2026 Tous droits réservés.": "© 2026 Todos los derechos reservados.",
  "Assistant Camping": "Asistente del camping",
  "Réponses immédiates": "Respuestas inmediatas",
  "Réception": "Recepción",
  "Voir les horaires": "Ver horarios",
  "Passer en mode sombre": "Activar modo oscuro",
  "Passer en mode clair": "Activar modo claro",
  "Appeler la réception": "Llamar a recepción",
  "Changer le thème": "Cambiar tema",
  "Effacer": "Borrar",
  "Envoyer": "Enviar",
  "Ouvrir l'assistant": "Abrir el asistente",
  "Rechercher dans l'application": "Buscar en la aplicación",
  "Décrivez votre problème en quelques mots...": "Describe tu problema en pocas palabras...",
  "Ex : 42": "Ej.: 42",
  "Pour confirmation": "Para confirmación",
  "Pour qu'on vous rappelle si besoin": "Para poder llamarte si es necesario",
  "Rechercher une page, un service, une activité…": "Busca una página, un servicio o una actividad…",
  "Écrivez votre question…": "Escribe tu pregunta…",
  "Numéro uniquement": "Solo números",
  "Supermarchés": "Supermercados",
  "Santé": "Salud",
  "Petits Commerces": "Pequeños comercios",
  "Grandes surfaces et courses du quotidien": "Supermercados y compras del día a día",
  "Pharmacie, médecins et urgences": "Farmacia, médicos y urgencias",
  "Boulangerie, tabac et presse à Izernore": "Panadería, estanco y prensa en Izernore",
  "← Toutes les catégories": "← Todas las categorías",
  "Adresse": "Dirección",
  "Horaires": "Horarios",
  "Téléphone": "Teléfono",
  "Site web": "Sitio web",
  "💡 Pour le dépannage, pensez aussi à": "💡 Para compras de última hora, recuerda también",
  "l'épicerie du camping": "la tienda del camping",
  "Supermarché complet avec rayon boulangerie, le plus pratique pour les grosses courses.": "Supermercado completo con sección de panadería, el más práctico para la compra grande.",
  "Pratique au retour du lac de Nantua. Espace dédié aux camping-cars à côté du magasin.": "Práctico a la vuelta del lago de Nantua. Zona para autocaravanas junto a la tienda.",
  "Le plus grand choix de la région (hypermarché), avec station-service.": "La mayor variedad de la zona (hipermercado), con gasolinera.",
  "Enseigne discount bien connue de nos vacanciers européens.": "Una cadena de descuento muy conocida por nuestros visitantes europeos.",
  "La pharmacie la plus proche du camping. Équipe accueillante et de bon conseil.": "La farmacia más cercana al camping. Equipo acogedor y de buen consejo.",
  "Maison de santé regroupant médecins généralistes et autres praticiens.": "Centro de salud con médicos de cabecera y otros profesionales.",
  "Le service d'urgences le plus proche du camping.": "El servicio de urgencias más cercano al camping.",
  "Numéros d'urgence :": "Números de emergencia:",
  "15 (SAMU) · 112 (urgences européennes) · 3237 (pharmacie de garde)": "15 (SAMU ambulancia) · 112 (emergencias europeas) · 3237 (farmacia de guardia)",
  "En cas de besoin, la réception du camping est là pour vous aider :": "Si lo necesitas, la recepción del camping está para ayudarte:",
  "🥐 Pain frais et viennoiseries disponibles chaque matin": "🥐 Pan fresco y bollería disponibles cada mañana",
  "au camping": "en el camping",
  "Boulangerie artisanale : pains, pâtisseries et petit salon de thé avec terrasse.": "Panadería artesanal: panes, pasteles y un pequeño salón de té con terraza.",
  "Tabac, presse, jeux, souvenirs et petit dépannage alimentaire.": "Tabaco, prensa, juegos, recuerdos y productos básicos.",
  "Lun–Sam : 8h30–19h30 · Dim : 9h–12h30": "Lun–Sáb: 8:30–19:30 · Dom: 9:00–12:30",
  "Lun–Sam : 8h30–20h · Dim : 8h30–12h30": "Lun–Sáb: 8:30–20:00 · Dom: 8:30–12:30",
  "Lun–Sam : 8h–20h · Dim : 8h–12h15": "Lun–Sáb: 8:00–20:00 · Dom: 8:00–12:15",
  "Lun–Ven : 8h45–12h15 / 14h45–19h · Sam : 8h45–12h30": "Lun–Vie: 8:45–12:15 / 14:45–19:00 · Sáb: 8:45–12:30",
  "Lun–Ven : 8h–18h": "Lun–Vie: 8:00–18:00",
  "Lun, Mar, Jeu–Sam : 6h–19h · Dim : 6h–13h · Fermé le mercredi": "Lun, Mar, Jue–Sáb: 6:00–19:00 · Dom: 6:00–13:00 · Cerrado los miércoles",
  "Lun–Sam : 6h30–12h30 / 15h–19h · Dim : 7h–12h30": "Lun–Sáb: 6:30–12:30 / 15:00–19:00 · Dom: 7:00–12:30"
};

/* ── Horaires ── */
window.CP_I18N['es'] = Object.assign(window.CP_I18N['es'], {
  "Horaires": "Horarios",
  "Réception": "Recepción",
  "Snack": "Snack",
  "Bar": "Bar",
  "Espace Aquatique": "Zona Acuática",
  "Notre équipe est à votre disposition à l'accueil pour répondre à toutes vos questions !": "Nuestro equipo está a tu disposición en recepción para responder a todas tus preguntas.",
  "Basse Saison (Mai, Juin, Septembre)": "Temporada baja (mayo, junio, septiembre)",
  "Haute Saison (Juillet - Août)": "Temporada alta (julio - agosto)",
  "Dimanche - Vendredi": "Domingo - Viernes",
  "Samedi": "Sábado",
  "Lundi - Vendredi": "Lunes - Viernes",
  "Samedi & Dimanche": "Sábado y Domingo",
  "Services :": "Servicios:",
  "Planche de charcuteries et de fromages locales | Commande à la carte du bar/snack sans réservation | Soirée à thème sur réservation (uniquement en juillet/août)": "Tabla de embutidos y quesos locales | Pedido a la carta del bar/snack sin reserva | Noche temática con reserva (solo en julio/agosto)",
  "Du 15 mai au 15 septembre 2026": "Del 15 de mayo al 15 de septiembre de 2026",
  "Cocktails à la carte | Boissons alcoolisées, soft, bières, vins | Vente de glaces | Dépôt de pain à partir de 8h00": "Cócteles a la carta | Bebidas alcohólicas, refrescos, cervezas, vinos | Venta de helados | Depósito de pan a partir de las 8h",
  "Pain & Viennoiseries :": "Pan y bollería:",
  "Commande au plus tard la veille avant 18h pour le lendemain": "Pedido antes de las 18h del día anterior",
  "Baignade surveillée l'après-midi uniquement en haute saison.": "Baño vigilado solo por las tardes en temporada alta.",
  "Horaires :": "Horarios:",
  "De 10h00 à 19h00": "De 10:00 a 19:00",
  "Prix :": "Precio:",
  "Gratuit pour la clientèle du camping": "Gratuito para los clientes del camping",
  "Règles d'accès :": "Normas de acceso:",
  "- Bracelets obligatoires": "- Pulseras obligatorias",
  "- Short de bain interdit": "- Bermudas de baño prohibidos",
  "- Chaussures à laisser à l'entrée avant le pédiluve": "- Dejar el calzado a la entrada antes del pediluvio",
  "- Tongs autorisées": "- Se permiten chanclas",
  "Info :": "Información:",
  "Messieurs, vous avez oublié votre maillot de bain ? On en vend à la réception à 15€.": "Caballeros, ¿han olvidado el bañador? Los vendemos en recepción por 15€.",
  "Du 23 mai au 15 septembre 2026": "Del 23 de mayo al 15 de septiembre de 2026",
  "Ouverture : 30/04/2026 au 28/09/2026": "Apertura: 30/04/2026 al 28/09/2026"
});

/* ── Toutes pages ── */
window.CP_I18N['es'] = Object.assign(window.CP_I18N['es'], {
  "Activités de Plein Air": "Actividades al Aire Libre",
  "Activités Nautiques": "Actividades Acuáticas",
  "Activités Intérieur": "Actividades de Interior",
  "Activités nautiques": "Actividades acuáticas",
  "Activités disponibles selon la saison": "Actividades disponibles según la temporada",
  "Activités familiales et pour enfants": "Actividades familiares y para niños",
  "Avec ou sans réservation": "Con o sin reserva",
  "Consultez la réception pour les détails": "Consulte la recepción para más detalles",
  "Toute l'année": "Todo el año",
  "Tous les âges": "Todas las edades",
  "Informations": "Información",
  "Plein Air": "Aire libre",
  "Nautiques": "Acuáticas",
  "Intérieur": "Interior",
  "Baignade": "Baño",
  "Pédalo": "Patín acuático",
  "Canoë, Paddle": "Canoa, Paddle",
  "Canyoning": "Barranquismo",
  "Randonnées dans le Jura": "Senderismo en el Jura",
  "Randonnées dans l'Ain": "Senderismo en el Ain",
  "Randonnées - Jura": "Senderismo - Jura",
  "Randonnées et balades": "Senderismo y paseos",
  "Balade équestre": "Paseo a caballo",
  "Ouverture": "Horario de apertura",
  "Ouvert à l'année": "Abierto todo el año",
  "Ouvert 24/7": "Abierto 24/7",
  "Ouvert 7j/7 24h/24": "Abierto 7 días a la semana, 24 horas al día",
  "Ouverture possible sur réservation": "Apertura posible bajo reserva",
  "Conseils": "Consejos",
  "Conseil :": "Consejo:",
  "Bon plan :": "Buena idea:",
  "Bon à savoir": "Bueno saberlo",
  "Astuce :": "Truco:",
  "Indications :": "Indicaciones:",
  "Période d'ouverture": "Período de apertura",
  "Retour départ": "Vuelve al inicio",
  "Point haut": "Punto más alto",
  "Point bas": "Punto más bajo",
  "Dénivelé +": "Desnivel positivo",
  "Dénivelé -": "Desnivel negativo",
  "Distance": "Distancia",
  "Durée": "Duración",
  "Facile": "Fácil",
  "Moyenne": "Moderado",
  "Difficile": "Difícil",
  "Kayak 1 place": "Kayak individual",
  "Kayak 2 places": "Kayak doble",
  "Paddle": "Tabla de paddle",
  "Gilet obligatoire": "Chaleco obligatorio",
  "Rangement inclus": "Almacenamiento incluido",
  "Libre service": "Autoservicio",
  "Payez seul !": "¡Pague usted mismo!",
  "Code par SMS": "Código por SMS",
  "Pour votre sécurité": "Para su seguridad",
  "Accès libre": "Acceso libre",
  "LOCATION DE KAYAK ET DE PADDLE EN LIBRE-SERVICE": "ALQUILER DE KAYAK Y PADDLE EN AUTOSERVICIO",
  "Réservez en ligne et ayez la liberté de payer où vous le souhaitez, quand vous souhaitez.": "Reserve en línea y pague donde y cuando quiera.",
  "La station de kayak et de paddle est en bas du camping (juste devant le lac). Si vous rencontrez un problème lors de la location, contactez-nous !": "La estación de kayak y paddle está al pie del camping (justo frente al lago). ¡Si tiene algún problema con el alquiler, contáctenos!",
  "Prix": "Precios",
  "Voir le site internet pour les tarifs": "Ver precios en el sitio web",
  "Voir le site internet pour les autres tarifs": "Ver otros precios en el sitio web",
  "Voir site internet": "Ver sitio web",
  "Tarifs à consulter auprès de l'organisateur": "Precios a consultar con el organizador",
  "Tarif réduit": "Precio reducido",
  "Réservation": "Reserva",
  "Réservation obligatoire. Ne nécessite aucune préparation ni aptitude particulière.": "Reserva obligatoria. No requiere preparación ni aptitud especial.",
  "Localisation": "Ubicación",
  "Trajet": "Tiempo de desplazamiento",
  "Environ 15 minutes en voiture": "Unos 15 minutos en coche",
  "Environ 15 minutes du camping en voiture": "Unos 15 minutos del camping en coche",
  "Environ 20 minutes du camping en voiture": "Unos 20 minutos del camping en coche",
  "Environ 25 minutes du camping en voiture": "Unos 25 minutos del camping en coche",
  "Environ 45 minutes du camping en voiture": "Unos 45 minutos del camping en coche",
  "Recharge à 15 minutes du Camping": "Carga a 15 minutos del camping",
  "Oyonnax — à 15 minutes du camping": "Oyonnax — a 15 minutos del camping",
  "Recharge disponible aux alentours du camping": "Recarga disponible cerca del camping",
  "Barrière": "Barrera",
  "Accès au camping": "Acceso al camping",
  "Vitesse de circulation": "Límite de velocidad",
  "La barrière est ouverte de 8h00 à 23h00 tous les jours. Pour entrer dans le camping, utilisez le code indiqué sur votre enveloppe d'accueil. En cas d'arrivée nocturne (fermeture de la barrière) : Vous pouvez stationner votre voiture sur le parking visiteurs devant le camping et rejoindre votre emplacement à pied.": "La barrera está abierta todos los días de 8:00 a 23:00. Use el código de su sobre de bienvenida para entrar. En caso de llegada nocturna: puede aparcar en el aparcamiento de visitantes y caminar hasta su parcela.",
  "La vitesse maximale autorisée dans le camping est de 10 km/h. Nous vous prions de bien vouloir respecter cette vitesse de circulation pour le respect de tout le monde et éviter tous risque d'accident.": "La velocidad máxima permitida en el camping es de 10 km/h. Por favor, respétela para la seguridad de todos.",
  "Heure limite de départ": "Hora límite de salida",
  "Remise des clés": "Entrega de llaves",
  "À la réception — ou boite en bois à l'entrée du camping si départ avant 9h00": "En recepción — o en la caja de madera a la entrada si sale antes de las 9h",
  "Procédure d'arrivée : check-in": "Procedimiento de llegada: check-in",
  "Procédure de sortie : check-out": "Procedimiento de salida: check-out",
  "Bienvenue au Camping Paradis Les Gorges du Haut-Bugey": "Bienvenido al Camping Paradis Les Gorges du Haut-Bugey",
  "Ça y est, les vacances peuvent commencer !": "¡Ya empiezan las vacaciones!",
  "Dans cette enveloppe, vous trouverez :": "En este sobre encontrará:",
  "Une fiche de bienvenue": "Un formulario de bienvenida",
  "Le plan du camping pour mieux vous repérer.": "El plano del camping para orientarse mejor.",
  "Les bracelets du camping à porter tout le long de votre séjour": "Las pulseras del camping que deberá llevar durante toda su estancia",
  "Code de la barrière": "Código de la barrera",
  "Vider les poubelles": "Vaciar la basura",
  "Faire la vaisselle": "Fregar los platos",
  "Au programme :": "En el programa:",
  "Présentation de l'équipe du camping": "Presentación del equipo del camping",
  "Planning des animations de la semaine": "Programa de animaciones de la semana",
  "Bons plans et informations touristiques de la région": "Consejos y información turística de la región",
  "Verre de bienvenue offert": "Copa de bienvenida gratuita",
  "Les dimanches à 19h.": "Los domingos a las 19h.",
  "Juillet et août uniquement": "Solo en julio y agosto",
  "Espace animation du camping": "Zona de animación del camping",
  "Période": "Período",
  "Un mini-club pour vos enfants": "Un mini-club para sus hijos",
  "De 9h30 à 12h et de 15h30 à 18h du 6 juillet au 31 août": "De 9:30 a 12:00 y de 15:30 a 18:00, del 6 de julio al 31 de agosto",
  "Gratuit, inclus dans la réservation": "Gratuito, incluido en la reserva",
  "Inscription obligatoire auprès de l'équipe d'animation lors du pot d'accueil le dimanche à 19h00.": "Inscripción obligatoria con el equipo de animación en la copa de bienvenida del domingo a las 19h.",
  "Juillet et août": "Julio y agosto",
  "Besoin d'aide pour vous repérer ?": "¿Necesita ayuda para orientarse?",
  "N'hésitez pas à passer à la réception, notre équipe vous indiquera le chemin avec plaisir !": "No dude en pasar por recepción, ¡nuestro equipo le indicará el camino con mucho gusto!",
  "WiFi Gratuit": "WiFi gratuito",
  "Réseau": "Red",
  "Camping-Paradis-WiFi": "Camping-Paradis-WiFi",
  "Tarif": "Tarifa",
  "Disponibilité": "Disponibilidad",
  "Couverture": "Cobertura",
  "Uniquement autour de la réception": "Solo alrededor de la recepción",
  "Code d'accès": "Código de acceso",
  "Pas de mot de passe, accès direct": "Sin contraseña, acceso directo",
  "Vitesse": "Velocidad",
  "Haut débit": "Alta velocidad",
  "Support": "Soporte",
  "Contactez la réception en cas de souci": "Contacte con recepción si tiene algún problema",
  "Service de Laverie": "Servicio de lavandería",
  "Application WASHIN": "Aplicación WASHIN",
  "Disponible sur Apple et Android": "Disponible en Apple y Android",
  "Paiement direct": "Pago directo",
  "Sur les machines disponibles": "En las máquinas disponibles",
  "Alimentation générale": "Alimentación general",
  "Horaires à consulter à la réception": "Horarios a consultar en recepción",
  "Baguettes": "Barras de pan",
  "Viennoiseries": "Bollería",
  "Pain frais du jour": "Pan fresco del día",
  "Croissants et pains au chocolat": "Cruasanes y panes de chocolate",
  "Commande": "Pedido",
  "Délai de commande": "Plazo de pedido",
  "Avant 18h la veille pour le lendemain": "Antes de las 18h del día anterior",
  "Retrait": "Recogida",
  "Directement au bar/snack du camping le matin": "Directamente en el bar/snack del camping por la mañana",
  "Au bar/snack du camping": "En el bar/snack del camping",
  "Notre bar": "Nuestro bar",
  "À la carte": "À la carte",
  "Sans réservation, sauf pour les soirées à thème": "Sin reserva, excepto para las noches temáticas",
  "Soirée moules frites — tous les vendredi": "Noche de mejillones con patatas — todos los viernes",
  "Soirée paëlla — tous les dimanches": "Noche de paella — todos los domingos",
  "Soirée barbecue + frites à volonté — tous les jeudis": "Barbacoa + patatas ilimitadas — todos los jueves",
  "À partir de 19h00": "A partir de las 19h",
  "À partir de 20h30": "A partir de las 20h30",
  "Spectacles & concerts en haute saison": "Espectáculos y conciertos en temporada alta",
  "Pêcher dans le Haut-Bugey": "Pesca en el Haut-Bugey",
  "Escalade, accrobranche et via ferrata": "Escalada, tirolinas y vía ferrata",
  "Partez à la découverte des paysages du Haut-Bugey : gorges, forêts, lacs et villages à explorer à pied ou à vélo !": "Descubra los paisajes del Haut-Bugey: gargantas, bosques, lagos y pueblos por explorar a pie o en bicicleta.",
  "Découvrez toutes les activités disponibles près du camping pour profiter au maximum de votre séjour !": "Descubra todas las actividades disponibles cerca del camping para aprovechar al máximo su estancia.",
  "Tous les jours sauf le mercredi — du 15 mai au 15 septembre 2026": "Todos los días excepto el miércoles — del 15 de mayo al 15 de septiembre de 2026",
  "Nous sommes ravis de vous inviter à un pot d'accueil le dimanche à 19h (en juillet/août). Cela sera l'occasion de faire connaissance, de vous présenter l'équipe, le planning d'animation et les informations touristiques de la région.": "Tenemos el placer de invitarle a una copa de bienvenida el domingo a las 19h (julio/agosto). Será una ocasión para conocernos, presentarle al equipo, el programa de animaciones y los consejos turísticos de la región."
});
