/* Camping Paradis — dictionnaire NL
   Cle: texte francais exact (espaces normalises). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['nl'] = {
  "Installer l'application": "Installeer de app",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Alle camping-info met één klik, zelfs zonder internet!",
  "Appuie sur le bouton": "Tik op de knop",
  "Partager": "Delen",
  "⬆️ en bas de Safari": "⬆️ onderaan in Safari",
  "Sélectionne": "Selecteer",
  "\"Sur l'écran d'accueil\"": "\"Zet op beginscherm\"",
  "Appuie sur": "Tik op",
  "\"Ajouter\"": "\"Voeg toe\"",
  "en haut à droite": "rechtsboven",
  "Appuie sur le menu": "Tik op het menu",
  "\"Ajouter à l'écran d'accueil\"": "\"Toevoegen aan startscherm\"",
  "Confirme en appuyant sur": "Bevestig door te tikken op",
  "✓ J'ai compris !": "✓ Begrepen!",
  "Continuer sans installer": "Doorgaan zonder installeren",
  "📱 Installer l'App": "📱 App installeren",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Vandaag",
  "Aujourd'hui": "Vandaag",
  "Chargement...": "Laden...",
  "Voir plus →": "Meer zien →",
  "Bon plan du moment": "Aanbieding van het moment",
  "Météo indisponible": "Weer niet beschikbaar",
  "Ciel dégagé": "Heldere lucht",
  "Principalement dégagé": "Overwegend helder",
  "Partiellement nuageux": "Gedeeltelijk bewolkt",
  "Couvert": "Bewolkt",
  "Brouillard": "Mist",
  "Brouillard givrant": "Aanvriezende mist",
  "Bruine légère": "Lichte motregen",
  "Bruine modérée": "Matige motregen",
  "Bruine dense": "Dichte motregen",
  "Pluie légère": "Lichte regen",
  "Pluie modérée": "Matige regen",
  "Pluie forte": "Zware regen",
  "Averses légères": "Lichte buien",
  "Averses modérées": "Matige buien",
  "Averses fortes": "Zware buien",
  "Neige légère": "Lichte sneeuw",
  "Neige modérée": "Matige sneeuw",
  "Neige forte": "Zware sneeuw",
  "Averses de neige": "Sneeuwbuien",
  "Averses de neige fortes": "Zware sneeuwbuien",
  "Orage": "Onweer",
  "Orage avec grêle": "Onweer met hagel",
  "Orage violent": "Zwaar onweer",
  "Variable": "Wisselvallig",
  "Vie au camping": "Het campingleven",
  "Horaires du Camping": "Openingstijden camping",
  "Réception, piscine, animations et services": "Receptie, zwembad, animatie en diensten",
  "Plan du camping": "Plattegrond van de camping",
  "Retrouvez votre emplacement et les équipements": "Vind uw plaats en de voorzieningen",
  "Tout savoir pour votre arrivée et départ": "Alles over uw aankomst en vertrek",
  "Pot d'accueil": "Welkomstborrel",
  "Rejoignez-nous pour un verre de bienvenue": "Kom langs voor een welkomstdrankje",
  "Service optionnel": "Optionele dienst",
  "Ménage fin de séjour": "Eindschoonmaak",
  "Partez l'esprit libre — on s'occupe de tout": "Vertrek zonder zorgen — wij regelen alles",
  "Service disponible sur demande": "Dienst beschikbaar op aanvraag",
  "Tarifs forfaitaires": "Vaste tarieven",
  "Mobil-home 2 ch.": "Stacaravan 2 slaapkamers",
  "Mobil-home 3 ch.": "Stacaravan 3 slaapkamers",
  "Inclus dans la prestation": "Inbegrepen in de dienst",
  "Nettoyage complet du logement": "Volledige schoonmaak van de accommodatie",
  "Sanitaires et cuisine": "Sanitair en keuken",
  "Gestion des déchets": "Afvalverwerking",
  "Confirmation par la réception": "Bevestiging door de receptie",
  "N° d'emplacement *": "Plaatsnummer *",
  "Date de départ *": "Vertrekdatum *",
  "Téléphone (optionnel)": "Telefoon (optioneel)",
  "Demander le ménage →": "Schoonmaak aanvragen →",
  "Annuler": "Annuleren",
  "Demande envoyée !": "Aanvraag verzonden!",
  "Notre équipe a bien reçu votre demande.": "Ons team heeft uw aanvraag ontvangen.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "Wij bevestigen het exacte tarief voor uw plaats.",
  "Fermer": "Sluiten",
  "Nos Services": "Onze diensten",
  "Kayak": "Kajak",
  "Explorez le lac du Val d'Oignin en kayak": "Verken het meer van Val d'Oignin per kajak",
  "Laverie": "Wasserette",
  "Service de laverie disponible 24h/24": "Wasservice 24 uur per dag beschikbaar",
  "Locations Diverses": "Diverse verhuur",
  "Locations diverses": "Diverse verhuur",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbecue, beddengoed, babykit, handdoeken",
  "Connexion internet gratuite": "Gratis internetverbinding",
  "Restauration & Bar": "Eten & Bar",
  "Burgers, salades et plats du jour": "Burgers, salades en dagschotels",
  "Cocktails, bières et boissons fraîches": "Cocktails, bier en frisdrank",
  "Épicerie": "Winkeltje",
  "Produits essentiels": "Dagelijkse boodschappen",
  "Petit-Déjeuner": "Ontbijt",
  "Petit-déjeuner": "Ontbijt",
  "Pain frais et viennoiseries chaque matin": "Vers brood en croissants elke ochtend",
  "Autour du camping": "Rondom de camping",
  "Activités à faire": "Activiteiten",
  "Kayak, randonnées, sports et loisirs en plein air": "Kajakken, wandelen, sport en buitenactiviteiten",
  "Restaurants": "Restaurants",
  "Les meilleures tables autour du camping": "De beste restaurants in de buurt",
  "À visiter": "Bezienswaardigheden",
  "Gorges de l'Ain, viaduc, cascade et villages": "Kloven van de Ain, viaduct, waterval en dorpjes",
  "Randonnées et Balades": "Wandelingen",
  "Sentiers balisés pour tous les niveaux": "Bewegwijzerde paden voor elk niveau",
  "Marchés": "Markten",
  "Producteurs locaux et marchés de la région": "Lokale producenten en streekmarkten",
  "Commerces": "Winkels",
  "Supermarchés et commerces à proximité": "Supermarkten en winkels in de buurt",
  "Animations": "Animatie",
  "Programme de la semaine": "Weekprogramma",
  "Activités, soirées et événements à ne pas manquer": "Activiteiten, avonden en evenementen die u niet mag missen",
  "Club enfants": "Kinderclub",
  "Ateliers et aventures pour les 6-12 ans": "Workshops en avonturen voor 6-12 jaar",
  "Montez sur scène et brillez devant tout le camping !": "Sta op het podium en schitter voor de hele camping!",
  "Circulation": "Verkeer",
  "Horaires de la barrière": "Openingstijden slagboom",
  "Entrées et sorties du camping : plages horaires": "In- en uitritten van de camping: tijdsloten",
  "Véhicule électrique": "Elektrische auto",
  "Recharge disponible sur site — infos et tarifs": "Opladen mogelijk op het terrein — info en tarieven",
  "Signaler un problème": "Een probleem melden",
  "Notre équipe intervient dans les plus brefs délais.": "Ons team komt zo snel mogelijk in actie.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Beschrijf uw situatie en wij nemen snel contact met u op.",
  "Type de problème *": "Soort probleem *",
  "Choisir...": "Kies...",
  "🚿 Sanitaires": "🚿 Sanitair",
  "🔌 Électricité / Eau": "🔌 Elektriciteit / Water",
  "🔊 Nuisances sonores": "🔊 Geluidsoverlast",
  "🗑️ Propreté": "🗑️ Netheid",
  "🌿 Végétation / Terrain": "🌿 Beplanting / Terrein",
  "🚗 Circulation / Barrière": "🚗 Verkeer / Slagboom",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurant / Winkeltje",
  "🏊 Piscine": "🏊 Zwembad",
  "❓ Autre": "❓ Anders",
  "Description *": "Beschrijving *",
  "Envoyer le signalement →": "Melding versturen →",
  "Signalement envoyé !": "Melding verzonden!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Ons team heeft uw bericht ontvangen en komt zo snel mogelijk in actie.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Bedankt dat u ons helpt uw verblijf te verbeteren 🙏",
  "© 2026 Tous droits réservés.": "© 2026 Alle rechten voorbehouden.",
  "Assistant Camping": "Camping-assistent",
  "Réponses immédiates": "Direct antwoord",
  "Réception": "Receptie",
  "Voir les horaires": "Bekijk de openingstijden",
  "Passer en mode sombre": "Donkere modus",
  "Passer en mode clair": "Lichte modus",
  "Appeler la réception": "Bel de receptie",
  "Changer le thème": "Thema wijzigen",
  "Effacer": "Wissen",
  "Envoyer": "Versturen",
  "Ouvrir l'assistant": "Open de assistent",
  "Rechercher dans l'application": "Zoeken in de app",
  "Décrivez votre problème en quelques mots...": "Beschrijf uw probleem in een paar woorden...",
  "Ex : 42": "Bijv. 42",
  "Pour confirmation": "Ter bevestiging",
  "Pour qu'on vous rappelle si besoin": "Zodat we u indien nodig kunnen terugbellen",
  "Rechercher une page, un service, une activité…": "Zoek een pagina, dienst of activiteit…",
  "Écrivez votre question…": "Typ uw vraag…",
  "Numéro uniquement": "Alleen cijfers",
  "Supermarchés": "Supermarkten",
  "Santé": "Gezondheid",
  "Petits Commerces": "Kleine winkels",
  "Grandes surfaces et courses du quotidien": "Supermarkten en dagelijkse boodschappen",
  "Pharmacie, médecins et urgences": "Apotheek, artsen en spoedgevallen",
  "Boulangerie, tabac et presse à Izernore": "Bakkerij, tabakszaak en kiosk in Izernore",
  "← Toutes les catégories": "← Alle categorieën",
  "Adresse": "Adres",
  "Horaires": "Openingstijden",
  "Téléphone": "Telefoon",
  "Site web": "Website",
  "💡 Pour le dépannage, pensez aussi à": "💡 Voor kleine boodschappen is er ook",
  "l'épicerie du camping": "het campingwinkeltje",
  "Supermarché complet avec rayon boulangerie, le plus pratique pour les grosses courses.": "Volledige supermarkt met bakkerijafdeling, het handigst voor grote boodschappen.",
  "Pratique au retour du lac de Nantua. Espace dédié aux camping-cars à côté du magasin.": "Handig op de terugweg van het meer van Nantua. Speciale camperplaats naast de winkel.",
  "Le plus grand choix de la région (hypermarché), avec station-service.": "De grootste keuze van de regio (hypermarkt), met tankstation.",
  "Enseigne discount bien connue de nos vacanciers européens.": "Een discountketen die onze Europese gasten goed kennen.",
  "La pharmacie la plus proche du camping. Équipe accueillante et de bon conseil.": "De dichtstbijzijnde apotheek bij de camping. Vriendelijk team met goed advies.",
  "Maison de santé regroupant médecins généralistes et autres praticiens.": "Gezondheidscentrum met huisartsen en andere zorgverleners.",
  "Le service d'urgences le plus proche du camping.": "De dichtstbijzijnde spoedeisende hulp bij de camping.",
  "Numéros d'urgence :": "Alarmnummers:",
  "15 (SAMU) · 112 (urgences européennes) · 3237 (pharmacie de garde)": "15 (SAMU ambulance) · 112 (Europees alarmnummer) · 3237 (dienstapotheek)",
  "En cas de besoin, la réception du camping est là pour vous aider :": "Hulp nodig? De receptie van de camping staat voor u klaar:",
  "🥐 Pain frais et viennoiseries disponibles chaque matin": "🥐 Vers brood en croissants elke ochtend verkrijgbaar",
  "au camping": "op de camping",
  "Boulangerie artisanale : pains, pâtisseries et petit salon de thé avec terrasse.": "Ambachtelijke bakkerij: brood, gebak en een klein theesalon met terras.",
  "Tabac, presse, jeux, souvenirs et petit dépannage alimentaire.": "Tabak, kranten, spellen, souvenirs en wat basisproducten.",
  "Lun–Sam : 8h30–19h30 · Dim : 9h–12h30": "Ma–za: 8.30–19.30 · Zo: 9.00–12.30",
  "Lun–Sam : 8h30–20h · Dim : 8h30–12h30": "Ma–za: 8.30–20.00 · Zo: 8.30–12.30",
  "Lun–Sam : 8h–20h · Dim : 8h–12h15": "Ma–za: 8.00–20.00 · Zo: 8.00–12.15",
  "Lun–Ven : 8h45–12h15 / 14h45–19h · Sam : 8h45–12h30": "Ma–vr: 8.45–12.15 / 14.45–19.00 · Za: 8.45–12.30",
  "Lun–Ven : 8h–18h": "Ma–vr: 8.00–18.00",
  "Lun, Mar, Jeu–Sam : 6h–19h · Dim : 6h–13h · Fermé le mercredi": "Ma, di, do–za: 6.00–19.00 · Zo: 6.00–13.00 · Woensdag gesloten",
  "Lun–Sam : 6h30–12h30 / 15h–19h · Dim : 7h–12h30": "Ma–za: 6.30–12.30 / 15.00–19.00 · Zo: 7.00–12.30"
};

/* ── Horaires ── */
window.CP_I18N['nl'] = Object.assign(window.CP_I18N['nl'], {
  "Horaires": "Openingstijden",
  "Réception": "Receptie",
  "Snack": "Snackbar",
  "Bar": "Bar",
  "Espace Aquatique": "Zwemgebied",
  "Notre équipe est à votre disposition à l'accueil pour répondre à toutes vos questions !": "Ons team staat voor u klaar bij de receptie om al uw vragen te beantwoorden!",
  "Basse Saison (Mai, Juin, Septembre)": "Laagseizoen (mei, juni, september)",
  "Haute Saison (Juillet - Août)": "Hoogseizoen (juli - augustus)",
  "Dimanche - Vendredi": "Zondag - Vrijdag",
  "Samedi": "Zaterdag",
  "Lundi - Vendredi": "Maandag - Vrijdag",
  "Samedi & Dimanche": "Zaterdag & Zondag",
  "Services :": "Diensten:",
  "Planche de charcuteries et de fromages locales | Commande à la carte du bar/snack sans réservation | Soirée à thème sur réservation (uniquement en juillet/août)": "Vleeswaren- en kaasplank | À la carte bestellen zonder reservering | Thema-avond op reservering (alleen juli/augustus)",
  "Du 15 mai au 15 septembre 2026": "Van 15 mei tot 15 september 2026",
  "Cocktails à la carte | Boissons alcoolisées, soft, bières, vins | Vente de glaces | Dépôt de pain à partir de 8h00": "À la carte cocktails | Alcoholische dranken, frisdrank, bier, wijn | IJsverkoop | Brood beschikbaar vanaf 8:00",
  "Pain & Viennoiseries :": "Brood & Gebak:",
  "Commande au plus tard la veille avant 18h pour le lendemain": "Bestelling uiterlijk de dag ervoor vóór 18:00 voor de volgende ochtend",
  "Baignade surveillée l'après-midi uniquement en haute saison.": "Toezicht op zwemmen alleen 's middags in het hoogseizoen.",
  "Horaires :": "Openingstijden:",
  "De 10h00 à 19h00": "Van 10:00 tot 19:00",
  "Prix :": "Prijs:",
  "Gratuit pour la clientèle du camping": "Gratis voor campinggasten",
  "Règles d'accès :": "Toegangsregels:",
  "- Bracelets obligatoires": "- Polsbandjes verplicht",
  "- Short de bain interdit": "- Zwembroeken niet toegestaan",
  "- Chaussures à laisser à l'entrée avant le pédiluve": "- Schoenen achterlaten bij de ingang vóór het voetbad",
  "- Tongs autorisées": "- Slippers toegestaan",
  "Info :": "Info:",
  "Messieurs, vous avez oublié votre maillot de bain ? On en vend à la réception à 15€.": "Heren, zwembroek vergeten? We verkopen ze bij de receptie voor €15.",
  "Du 23 mai au 15 septembre 2026": "Van 23 mei tot 15 september 2026",
  "Ouverture : 30/04/2026 au 28/09/2026": "Open: 30/04/2026 t/m 28/09/2026"
});

/* ── checkin.html textes manquants ── */
window.CP_I18N['nl'] = Object.assign(window.CP_I18N['nl'], {
  "Votre semaine de vacances touche à sa fin et nous sommes aussi triste de vous voir partir.": "Uw vakantieweek loopt op zijn einde en wij zijn ook bedroefd u te zien vertrekken.",
  "Si vous avez séjourné en hébergement (chalet/mobilhome/cottage), il faudra quitter l'hébergement au plus tard à": "Als u in een accommodatie (chalet/stacaravan/cottage) heeft verbleven, dient u deze te verlaten uiterlijk om",
  "Nous n'effectuons pas d'état des lieux pendant votre départ.": "Wij voeren geen toestandscontrole uit bij uw vertrek.",
  "Les équipes de ménages veilleront à ce que l'hébergement soit le même que lorsqu'il vous a été confié. En cas de problème, nous vous contacterons par téléphone.": "De schoonmaakteams zorgen ervoor dat de accommodatie in dezelfde staat is als bij de overdracht. Bij problemen nemen wij telefonisch contact met u op.",
  "Nous vous demandons de rendre l'hébergement aussi propre qu'il vous a été donné.": "Wij vragen u de accommodatie even schoon achter te laten als u haar heeft ontvangen.",
  "Vous pouvez remettre les clés à la réception avant de partir. Dans le cas où vous souhaitez partir très tôt et que la réception n'est pas ouverte (avant 9h00), nous avons mis en place une boite en bois à l'entrée du Camping. Vous pourrez y déposer directement les clés.": "U kunt de sleutels voor vertrek inleveren bij de receptie. Als u zeer vroeg wilt vertrekken en de receptie niet open is (voor 9u00), hebben wij een houten box bij de ingang geplaatst waar u de sleutels direct kunt achterlaten.",
  "Vous avez souscrit au forfait ménage, nous vous demandons seulement de :*": "Als u het schoonmaakpakket heeft geboekt, vragen wij u alleen:*",
  "Vous n'avez pas souscrit au forfait ménage :": "Als u geen schoonmaakpakket heeft geboekt:",
  "Remise des clés :": "Sleutelinlevering:",
  "10h00 pour les hébergements": "10u00 voor accommodaties",
  "Pour vous accompagner au mieux pendant votre séjour, nous vous avons remis à la réception une enveloppe contenant toutes les informations utiles.": "Om u zo goed mogelijk te begeleiden tijdens uw verblijf, hebben wij u bij de receptie een envelop overhandigd met alle nuttige informatie.",
  "Un mémo \"Tri et compost\" : toutes les poubelles sont situées à l'entrée du camping. Merci de respecter les consignes, on compte sur vous pour préserver notre belle nature.": "Een memo \"Afvalscheiding en compost\": alle vuilnisbakken bevinden zich bij de ingang van de camping. Volg de instructies — wij rekenen op u!",
  "Un QR code pour accéder directement à notre application et profiter de tous nos services (animations, infos pratiques, lieux à visiter…).": "Een QR-code voor directe toegang tot onze app en alle diensten (animatie, praktische info, bezienswaardigheden…).",
  ": il est inscrit directement sur l'enveloppe remise à votre arrivée.": ": Hij staat direct op de envelop die u bij aankomst heeft ontvangen.",
  ": vous n'avez pas besoin de code pour sortir du camping, un capteur est installé au sol.": ": U heeft geen code nodig om de camping te verlaten — er is een sensor in de grond ingebouwd.",
  ": à compléter avec les informations des participants, votre avis sur la propreté du logement, et un espace pour toute remarque à nous faire remonter.": ": In te vullen met gegevens van deelnemers, uw mening over de netheid van de accommodatie en een ruimte voor opmerkingen."
});
