/* Camping Paradis — dictionnaire NL
   Cle: texte francais exact (espaces normalises). */
window.CP_I18N = window.CP_I18N || {};
window.CP_I18N['nl'] = {
  "Installer l'application": "Installeer de app",
  "Accédez à toutes les infos du camping en un clic, même sans connexion !": "Alle camping-info met één klik, zelfs zonder internet!",
  "Appuie sur le bouton": "Tik op de knop",
  "Partager": "Delen",
  "⬆️ en bas de Safari": "⬆️ onderaan in Safari",
  "Sélectionne": "Selecteer",
  "\"Sur l'écran d'accueil\"": "\"Zet op beginscherm\"",
  "Appuie sur": "Tik op",
  "\"Ajouter\"": "\"Voeg toe\"",
  "en haut à droite": "rechtsboven",
  "Appuie sur le menu": "Tik op het menu",
  "\"Ajouter à l'écran d'accueil\"": "\"Toevoegen aan startscherm\"",
  "Confirme en appuyant sur": "Bevestig door te tikken op",
  "✓ J'ai compris !": "✓ Begrepen!",
  "Continuer sans installer": "Doorgaan zonder installeren",
  "📱 Installer l'App": "📱 App installeren",
  "Matafelon-Granges · Aujourd'hui": "Matafelon-Granges · Vandaag",
  "Aujourd'hui": "Vandaag",
  "Chargement...": "Laden...",
  "Voir plus →": "Meer zien →",
  "Bon plan du moment": "Aanbieding van het moment",
  "Météo indisponible": "Weer niet beschikbaar",
  "Ciel dégagé": "Heldere lucht",
  "Principalement dégagé": "Overwegend helder",
  "Partiellement nuageux": "Gedeeltelijk bewolkt",
  "Couvert": "Bewolkt",
  "Brouillard": "Mist",
  "Brouillard givrant": "Aanvriezende mist",
  "Bruine légère": "Lichte motregen",
  "Bruine modérée": "Matige motregen",
  "Bruine dense": "Dichte motregen",
  "Pluie légère": "Lichte regen",
  "Pluie modérée": "Matige regen",
  "Pluie forte": "Zware regen",
  "Averses légères": "Lichte buien",
  "Averses modérées": "Matige buien",
  "Averses fortes": "Zware buien",
  "Neige légère": "Lichte sneeuw",
  "Neige modérée": "Matige sneeuw",
  "Neige forte": "Zware sneeuw",
  "Averses de neige": "Sneeuwbuien",
  "Averses de neige fortes": "Zware sneeuwbuien",
  "Orage": "Onweer",
  "Orage avec grêle": "Onweer met hagel",
  "Orage violent": "Zwaar onweer",
  "Variable": "Wisselvallig",
  "Vie au camping": "Het campingleven",
  "Horaires du Camping": "Openingstijden camping",
  "Réception, piscine, animations et services": "Receptie, zwembad, animatie en diensten",
  "Plan du camping": "Plattegrond van de camping",
  "Retrouvez votre emplacement et les équipements": "Vind uw plaats en de voorzieningen",
  "Tout savoir pour votre arrivée et départ": "Alles over uw aankomst en vertrek",
  "Pot d'accueil": "Welkomstborrel",
  "Rejoignez-nous pour un verre de bienvenue": "Kom langs voor een welkomstdrankje",
  "Service optionnel": "Optionele dienst",
  "Ménage fin de séjour": "Eindschoonmaak",
  "Partez l'esprit libre — on s'occupe de tout": "Vertrek zonder zorgen — wij regelen alles",
  "Service disponible sur demande": "Dienst beschikbaar op aanvraag",
  "Tarifs forfaitaires": "Vaste tarieven",
  "Mobil-home 2 ch.": "Stacaravan 2 slaapkamers",
  "Mobil-home 3 ch.": "Stacaravan 3 slaapkamers",
  "Inclus dans la prestation": "Inbegrepen in de dienst",
  "Nettoyage complet du logement": "Volledige schoonmaak van de accommodatie",
  "Sanitaires et cuisine": "Sanitair en keuken",
  "Gestion des déchets": "Afvalverwerking",
  "Confirmation par la réception": "Bevestiging door de receptie",
  "N° d'emplacement *": "Plaatsnummer *",
  "Date de départ *": "Vertrekdatum *",
  "Téléphone (optionnel)": "Telefoon (optioneel)",
  "Demander le ménage →": "Schoonmaak aanvragen →",
  "Annuler": "Annuleren",
  "Demande envoyée !": "Aanvraag verzonden!",
  "Notre équipe a bien reçu votre demande.": "Ons team heeft uw aanvraag ontvangen.",
  "Nous vous confirmons le tarif exact selon votre emplacement.": "Wij bevestigen het exacte tarief voor uw plaats.",
  "Fermer": "Sluiten",
  "Nos Services": "Onze diensten",
  "Kayak": "Kajak",
  "Explorez le lac du Val d'Oignin en kayak": "Verken het meer van Val d'Oignin per kajak",
  "Laverie": "Wasserette",
  "Service de laverie disponible 24h/24": "Wasservice 24 uur per dag beschikbaar",
  "Locations Diverses": "Diverse verhuur",
  "Locations diverses": "Diverse verhuur",
  "Barbecue, draps, kit bébé, linge de toilettes": "Barbecue, beddengoed, babykit, handdoeken",
  "Connexion internet gratuite": "Gratis internetverbinding",
  "Restauration & Bar": "Eten & Bar",
  "Burgers, salades et plats du jour": "Burgers, salades en dagschotels",
  "Cocktails, bières et boissons fraîches": "Cocktails, bier en frisdrank",
  "Épicerie": "Winkeltje",
  "Produits essentiels": "Dagelijkse boodschappen",
  "Petit-Déjeuner": "Ontbijt",
  "Petit-déjeuner": "Ontbijt",
  "Pain frais et viennoiseries chaque matin": "Vers brood en croissants elke ochtend",
  "Autour du camping": "Rondom de camping",
  "Activités à faire": "Activiteiten",
  "Kayak, randonnées, sports et loisirs en plein air": "Kajakken, wandelen, sport en buitenactiviteiten",
  "Restaurants": "Restaurants",
  "Les meilleures tables autour du camping": "De beste restaurants in de buurt",
  "À visiter": "Bezienswaardigheden",
  "Gorges de l'Ain, viaduc, cascade et villages": "Kloven van de Ain, viaduct, waterval en dorpjes",
  "Randonnées et Balades": "Wandelingen",
  "Sentiers balisés pour tous les niveaux": "Bewegwijzerde paden voor elk niveau",
  "Marchés": "Markten",
  "Producteurs locaux et marchés de la région": "Lokale producenten en streekmarkten",
  "Commerces": "Winkels",
  "Supermarchés et commerces à proximité": "Supermarkten en winkels in de buurt",
  "Animations": "Animatie",
  "Programme de la semaine": "Weekprogramma",
  "Activités, soirées et événements à ne pas manquer": "Activiteiten, avonden en evenementen die u niet mag missen",
  "Club enfants": "Kinderclub",
  "Ateliers et aventures pour les 6-12 ans": "Workshops en avonturen voor 6-12 jaar",
  "Montez sur scène et brillez devant tout le camping !": "Sta op het podium en schitter voor de hele camping!",
  "Circulation": "Verkeer",
  "Horaires de la barrière": "Openingstijden slagboom",
  "Entrées et sorties du camping : plages horaires": "In- en uitritten van de camping: tijdsloten",
  "Véhicule électrique": "Elektrische auto",
  "Recharge disponible sur site — infos et tarifs": "Opladen mogelijk op het terrein — info en tarieven",
  "Signaler un problème": "Een probleem melden",
  "Notre équipe intervient dans les plus brefs délais.": "Ons team komt zo snel mogelijk in actie.",
  "Décrivez votre situation et nous revenons vers vous rapidement.": "Beschrijf uw situatie en wij nemen snel contact met u op.",
  "Type de problème *": "Soort probleem *",
  "Choisir...": "Kies...",
  "🚿 Sanitaires": "🚿 Sanitair",
  "🔌 Électricité / Eau": "🔌 Elektriciteit / Water",
  "🔊 Nuisances sonores": "🔊 Geluidsoverlast",
  "🗑️ Propreté": "🗑️ Netheid",
  "🌿 Végétation / Terrain": "🌿 Beplanting / Terrein",
  "🚗 Circulation / Barrière": "🚗 Verkeer / Slagboom",
  "🍽️ Restaurant / Épicerie": "🍽️ Restaurant / Winkeltje",
  "🏊 Piscine": "🏊 Zwembad",
  "❓ Autre": "❓ Anders",
  "Description *": "Beschrijving *",
  "Envoyer le signalement →": "Melding versturen →",
  "Signalement envoyé !": "Melding verzonden!",
  "Notre équipe a bien reçu votre message et interviendra dans les plus brefs délais.": "Ons team heeft uw bericht ontvangen en komt zo snel mogelijk in actie.",
  "Merci de nous aider à améliorer votre séjour 🙏": "Bedankt dat u ons helpt uw verblijf te verbeteren 🙏",
  "© 2026 Tous droits réservés.": "© 2026 Alle rechten voorbehouden.",
  "Assistant Camping": "Camping-assistent",
  "Réponses immédiates": "Direct antwoord",
  "Réception": "Receptie",
  "Voir les horaires": "Bekijk de openingstijden",
  "Passer en mode sombre": "Donkere modus",
  "Passer en mode clair": "Lichte modus",
  "Appeler la réception": "Bel de receptie",
  "Changer le thème": "Thema wijzigen",
  "Effacer": "Wissen",
  "Envoyer": "Versturen",
  "Ouvrir l'assistant": "Open de assistent",
  "Rechercher dans l'application": "Zoeken in de app",
  "Décrivez votre problème en quelques mots...": "Beschrijf uw probleem in een paar woorden...",
  "Ex : 42": "Bijv. 42",
  "Pour confirmation": "Ter bevestiging",
  "Pour qu'on vous rappelle si besoin": "Zodat we u indien nodig kunnen terugbellen",
  "Rechercher une page, un service, une activité…": "Zoek een pagina, dienst of activiteit…",
  "Écrivez votre question…": "Typ uw vraag…",
  "Numéro uniquement": "Alleen cijfers",
  "Supermarchés": "Supermarkten",
  "Santé": "Gezondheid",
  "Petits Commerces": "Kleine winkels",
  "Grandes surfaces et courses du quotidien": "Supermarkten en dagelijkse boodschappen",
  "Pharmacie, médecins et urgences": "Apotheek, artsen en spoedgevallen",
  "Boulangerie, tabac et presse à Izernore": "Bakkerij, tabakszaak en kiosk in Izernore",
  "← Toutes les catégories": "← Alle categorieën",
  "Adresse": "Adres",
  "Horaires": "Openingstijden",
  "Téléphone": "Telefoon",
  "Site web": "Website",
  "💡 Pour le dépannage, pensez aussi à": "💡 Voor kleine boodschappen is er ook",
  "l'épicerie du camping": "het campingwinkeltje",
  "Supermarché complet avec rayon boulangerie, le plus pratique pour les grosses courses.": "Volledige supermarkt met bakkerijafdeling, het handigst voor grote boodschappen.",
  "Pratique au retour du lac de Nantua. Espace dédié aux camping-cars à côté du magasin.": "Handig op de terugweg van het meer van Nantua. Speciale camperplaats naast de winkel.",
  "Le plus grand choix de la région (hypermarché), avec station-service.": "De grootste keuze van de regio (hypermarkt), met tankstation.",
  "Enseigne discount bien connue de nos vacanciers européens.": "Een discountketen die onze Europese gasten goed kennen.",
  "La pharmacie la plus proche du camping. Équipe accueillante et de bon conseil.": "De dichtstbijzijnde apotheek bij de camping. Vriendelijk team met goed advies.",
  "Maison de santé regroupant médecins généralistes et autres praticiens.": "Gezondheidscentrum met huisartsen en andere zorgverleners.",
  "Le service d'urgences le plus proche du camping.": "De dichtstbijzijnde spoedeisende hulp bij de camping.",
  "Numéros d'urgence :": "Alarmnummers:",
  "15 (SAMU) · 112 (urgences européennes) · 3237 (pharmacie de garde)": "15 (SAMU ambulance) · 112 (Europees alarmnummer) · 3237 (dienstapotheek)",
  "En cas de besoin, la réception du camping est là pour vous aider :": "Hulp nodig? De receptie van de camping staat voor u klaar:",
  "🥐 Pain frais et viennoiseries disponibles chaque matin": "🥐 Vers brood en croissants elke ochtend verkrijgbaar",
  "au camping": "op de camping",
  "Boulangerie artisanale : pains, pâtisseries et petit salon de thé avec terrasse.": "Ambachtelijke bakkerij: brood, gebak en een klein theesalon met terras.",
  "Tabac, presse, jeux, souvenirs et petit dépannage alimentaire.": "Tabak, kranten, spellen, souvenirs en wat basisproducten.",
  "Lun–Sam : 8h30–19h30 · Dim : 9h–12h30": "Ma–za: 8.30–19.30 · Zo: 9.00–12.30",
  "Lun–Sam : 8h30–20h · Dim : 8h30–12h30": "Ma–za: 8.30–20.00 · Zo: 8.30–12.30",
  "Lun–Sam : 8h–20h · Dim : 8h–12h15": "Ma–za: 8.00–20.00 · Zo: 8.00–12.15",
  "Lun–Ven : 8h45–12h15 / 14h45–19h · Sam : 8h45–12h30": "Ma–vr: 8.45–12.15 / 14.45–19.00 · Za: 8.45–12.30",
  "Lun–Ven : 8h–18h": "Ma–vr: 8.00–18.00",
  "Lun, Mar, Jeu–Sam : 6h–19h · Dim : 6h–13h · Fermé le mercredi": "Ma, di, do–za: 6.00–19.00 · Zo: 6.00–13.00 · Woensdag gesloten",
  "Lun–Sam : 6h30–12h30 / 15h–19h · Dim : 7h–12h30": "Ma–za: 6.30–12.30 / 15.00–19.00 · Zo: 7.00–12.30"
};

/* ── Horaires ── */
window.CP_I18N['nl'] = Object.assign(window.CP_I18N['nl'], {
  "Horaires": "Openingstijden",
  "Réception": "Receptie",
  "Snack": "Snackbar",
  "Bar": "Bar",
  "Espace Aquatique": "Zwemgebied",
  "Notre équipe est à votre disposition à l'accueil pour répondre à toutes vos questions !": "Ons team staat voor u klaar bij de receptie om al uw vragen te beantwoorden!",
  "Basse Saison (Mai, Juin, Septembre)": "Laagseizoen (mei, juni, september)",
  "Haute Saison (Juillet - Août)": "Hoogseizoen (juli - augustus)",
  "Dimanche - Vendredi": "Zondag - Vrijdag",
  "Samedi": "Zaterdag",
  "Lundi - Vendredi": "Maandag - Vrijdag",
  "Samedi & Dimanche": "Zaterdag & Zondag",
  "Services :": "Diensten:",
  "Planche de charcuteries et de fromages locales | Commande à la carte du bar/snack sans réservation | Soirée à thème sur réservation (uniquement en juillet/août)": "Vleeswaren- en kaasplank | À la carte bestellen zonder reservering | Thema-avond op reservering (alleen juli/augustus)",
  "Du 15 mai au 15 septembre 2026": "Van 15 mei tot 15 september 2026",
  "Cocktails à la carte | Boissons alcoolisées, soft, bières, vins | Vente de glaces | Dépôt de pain à partir de 8h00": "À la carte cocktails | Alcoholische dranken, frisdrank, bier, wijn | IJsverkoop | Brood beschikbaar vanaf 8:00",
  "Pain & Viennoiseries :": "Brood & Gebak:",
  "Commande au plus tard la veille avant 18h pour le lendemain": "Bestelling uiterlijk de dag ervoor vóór 18:00 voor de volgende ochtend",
  "Baignade surveillée l'après-midi uniquement en haute saison.": "Toezicht op zwemmen alleen 's middags in het hoogseizoen.",
  "Horaires :": "Openingstijden:",
  "De 10h00 à 19h00": "Van 10:00 tot 19:00",
  "Prix :": "Prijs:",
  "Gratuit pour la clientèle du camping": "Gratis voor campinggasten",
  "Règles d'accès :": "Toegangsregels:",
  "- Bracelets obligatoires": "- Polsbandjes verplicht",
  "- Short de bain interdit": "- Zwembroeken niet toegestaan",
  "- Chaussures à laisser à l'entrée avant le pédiluve": "- Schoenen achterlaten bij de ingang vóór het voetbad",
  "- Tongs autorisées": "- Slippers toegestaan",
  "Info :": "Info:",
  "Messieurs, vous avez oublié votre maillot de bain ? On en vend à la réception à 15€.": "Heren, zwembroek vergeten? We verkopen ze bij de receptie voor €15.",
  "Du 23 mai au 15 septembre 2026": "Van 23 mei tot 15 september 2026",
  "Ouverture : 30/04/2026 au 28/09/2026": "Open: 30/04/2026 t/m 28/09/2026"
});

/* ── Toutes pages ── */
window.CP_I18N['nl'] = Object.assign(window.CP_I18N['nl'], {
  "Activités de Plein Air": "Buitenactiviteiten",
  "Activités Nautiques": "Wateractiviteiten",
  "Activités Intérieur": "Binnenactiviteiten",
  "Activités nautiques": "Wateractiviteiten",
  "Activités disponibles selon la saison": "Activiteiten beschikbaar afhankelijk van het seizoen",
  "Activités familiales et pour enfants": "Familie- en kinderactiviteiten",
  "Avec ou sans réservation": "Met of zonder reservering",
  "Consultez la réception pour les détails": "Vraag de receptie voor details",
  "Toute l'année": "Het hele jaar",
  "Tous les âges": "Alle leeftijden",
  "Informations": "Informatie",
  "Plein Air": "Buiten",
  "Nautiques": "Water",
  "Intérieur": "Binnen",
  "Baignade": "Zwemmen",
  "Pédalo": "Waterfiets",
  "Canoë, Paddle": "Kano, Paddle",
  "Canyoning": "Canyoning",
  "Randonnées dans le Jura": "Wandelingen in de Jura",
  "Randonnées dans l'Ain": "Wandelingen in de Ain",
  "Randonnées - Jura": "Wandelingen - Jura",
  "Randonnées et balades": "Wandelingen en uitstapjes",
  "Balade équestre": "Paardrijden",
  "Ouverture": "Openingstijden",
  "Ouvert à l'année": "Het hele jaar open",
  "Ouvert 24/7": "24/7 open",
  "Ouvert 7j/7 24h/24": "7 dagen per week, 24 uur per dag open",
  "Ouverture possible sur réservation": "Opening mogelijk op reservering",
  "Conseils": "Tips",
  "Conseil :": "Tip:",
  "Bon plan :": "Handige tip:",
  "Bon à savoir": "Handig om te weten",
  "Astuce :": "Tip:",
  "Indications :": "Aanwijzingen:",
  "Période d'ouverture": "Openingsperiode",
  "Retour départ": "Keert terug naar start",
  "Point haut": "Hoogste punt",
  "Point bas": "Laagste punt",
  "Dénivelé +": "Hoogteverschil (stijging)",
  "Dénivelé -": "Hoogteverschil (daling)",
  "Distance": "Afstand",
  "Durée": "Duur",
  "Facile": "Makkelijk",
  "Moyenne": "Gemiddeld",
  "Difficile": "Moeilijk",
  "Kayak 1 place": "Eenpersoons kajak",
  "Kayak 2 places": "Tweepersoons kajak",
  "Paddle": "Sup-board",
  "Gilet obligatoire": "Zwemvest verplicht",
  "Rangement inclus": "Opslag inbegrepen",
  "Libre service": "Zelfbediening",
  "Payez seul !": "Betaal zelf!",
  "Code par SMS": "Code per sms",
  "Pour votre sécurité": "Voor uw veiligheid",
  "Accès libre": "Vrije toegang",
  "LOCATION DE KAYAK ET DE PADDLE EN LIBRE-SERVICE": "ZELFBEDIENINGSVERHUUR KAJAK EN PADDLE",
  "Réservez en ligne et ayez la liberté de payer où vous le souhaitez, quand vous souhaitez.": "Boek online en betaal waar en wanneer u wilt.",
  "La station de kayak et de paddle est en bas du camping (juste devant le lac). Si vous rencontrez un problème lors de la location, contactez-nous !": "Het kajak- en paddlestation bevindt zich aan het einde van de camping (vlak voor het meer). Neem contact met ons op als u problemen heeft!",
  "Prix": "Prijzen",
  "Voir le site internet pour les tarifs": "Zie website voor tarieven",
  "Voir le site internet pour les autres tarifs": "Zie website voor andere tarieven",
  "Voir site internet": "Zie website",
  "Tarifs à consulter auprès de l'organisateur": "Tarieven opvragen bij de organisator",
  "Tarif réduit": "Gereduceerd tarief",
  "Réservation": "Reservering",
  "Réservation obligatoire. Ne nécessite aucune préparation ni aptitude particulière.": "Reservering verplicht. Geen speciale voorbereiding of conditie vereist.",
  "Localisation": "Locatie",
  "Trajet": "Reistijd",
  "Environ 15 minutes en voiture": "Ongeveer 15 minuten rijden",
  "Environ 15 minutes du camping en voiture": "Ongeveer 15 minuten rijden van de camping",
  "Environ 20 minutes du camping en voiture": "Ongeveer 20 minuten rijden van de camping",
  "Environ 25 minutes du camping en voiture": "Ongeveer 25 minuten rijden van de camping",
  "Environ 45 minutes du camping en voiture": "Ongeveer 45 minuten rijden van de camping",
  "Recharge à 15 minutes du Camping": "Opladen op 15 minuten van de camping",
  "Oyonnax — à 15 minutes du camping": "Oyonnax — 15 minuten van de camping",
  "Recharge disponible aux alentours du camping": "Oplaadpunt beschikbaar in de buurt van de camping",
  "Barrière": "Slagboom",
  "Accès au camping": "Toegang tot de camping",
  "Vitesse de circulation": "Snelheidslimiet",
  "La barrière est ouverte de 8h00 à 23h00 tous les jours. Pour entrer dans le camping, utilisez le code indiqué sur votre enveloppe d'accueil. En cas d'arrivée nocturne (fermeture de la barrière) : Vous pouvez stationner votre voiture sur le parking visiteurs devant le camping et rejoindre votre emplacement à pied.": "De slagboom is elke dag open van 8:00 tot 23:00. Gebruik de code op uw welkomstenvelope om de camping binnen te komen. Bij aankomst 's nachts: parkeer uw auto op de bezoekersparkeerplaats voor de camping en loop naar uw standplaats.",
  "La vitesse maximale autorisée dans le camping est de 10 km/h. Nous vous prions de bien vouloir respecter cette vitesse de circulation pour le respect de tout le monde et éviter tous risque d'accident.": "De maximumsnelheid op de camping is 10 km/u. Gelieve deze limiet te respecteren voor ieders veiligheid.",
  "Heure limite de départ": "Vertrekuur",
  "Remise des clés": "Sleutelinlevering",
  "À la réception — ou boite en bois à l'entrée du camping si départ avant 9h00": "Bij de receptie — of in de houten box bij de ingang als u voor 9u00 vertrekt",
  "Procédure d'arrivée : check-in": "Aankomstprocedure: check-in",
  "Procédure de sortie : check-out": "Vertrekprocedure: check-out",
  "Bienvenue au Camping Paradis Les Gorges du Haut-Bugey": "Welkom bij Camping Paradis Les Gorges du Haut-Bugey",
  "Ça y est, les vacances peuvent commencer !": "De vakantie kan beginnen!",
  "Dans cette enveloppe, vous trouverez :": "In deze envelop vindt u:",
  "Une fiche de bienvenue": "Een welkomstformulier",
  "Le plan du camping pour mieux vous repérer.": "De campingplattegrond om u te oriënteren.",
  "Les bracelets du camping à porter tout le long de votre séjour": "De campingpolsbandjes om tijdens uw verblijf te dragen",
  "Code de la barrière": "Code slagboom",
  "Vider les poubelles": "De vuilnisbakken legen",
  "Faire la vaisselle": "De afwas doen",
  "Au programme :": "Op het programma:",
  "Présentation de l'équipe du camping": "Voorstelling van het campingteam",
  "Planning des animations de la semaine": "Weekprogramma animaties",
  "Bons plans et informations touristiques de la région": "Tips en toeristische informatie over de regio",
  "Verre de bienvenue offert": "Gratis welkomstdrankje",
  "Les dimanches à 19h.": "Zondags om 19u.",
  "Juillet et août uniquement": "Alleen in juli en augustus",
  "Espace animation du camping": "Animatieruimte van de camping",
  "Période": "Periode",
  "Un mini-club pour vos enfants": "Een mini-club voor uw kinderen",
  "De 9h30 à 12h et de 15h30 à 18h du 6 juillet au 31 août": "Van 9u30 tot 12u en van 15u30 tot 18u van 6 juli tot 31 augustus",
  "Gratuit, inclus dans la réservation": "Gratis, inbegrepen in de reservering",
  "Inscription obligatoire auprès de l'équipe d'animation lors du pot d'accueil le dimanche à 19h00.": "Inschrijving verplicht bij het animatieteam tijdens het welkomstdrankje op zondag om 19u.",
  "Juillet et août": "Juli en augustus",
  "Besoin d'aide pour vous repérer ?": "Hulp nodig bij het oriënteren?",
  "N'hésitez pas à passer à la réception, notre équipe vous indiquera le chemin avec plaisir !": "Kom gerust langs bij de receptie — ons team helpt u graag de weg!",
  "WiFi Gratuit": "Gratis WiFi",
  "Réseau": "Netwerk",
  "Camping-Paradis-WiFi": "Camping-Paradis-WiFi",
  "Tarif": "Tarief",
  "Disponibilité": "Beschikbaarheid",
  "Couverture": "Dekking",
  "Uniquement autour de la réception": "Alleen rond de receptie",
  "Code d'accès": "Toegangscode",
  "Pas de mot de passe, accès direct": "Geen wachtwoord nodig, directe toegang",
  "Vitesse": "Snelheid",
  "Haut débit": "Hoge snelheid",
  "Support": "Ondersteuning",
  "Contactez la réception en cas de souci": "Neem contact op met de receptie bij problemen",
  "Service de Laverie": "Wasservice",
  "Application WASHIN": "WASHIN-app",
  "Disponible sur Apple et Android": "Beschikbaar op Apple en Android",
  "Paiement direct": "Directe betaling",
  "Sur les machines disponibles": "Op de beschikbare machines",
  "Alimentation générale": "Algemene levensmiddelen",
  "Horaires à consulter à la réception": "Openingstijden opvragen bij de receptie",
  "Baguettes": "Stokbrood",
  "Viennoiseries": "Croissants en gebak",
  "Pain frais du jour": "Vers dagelijks brood",
  "Croissants et pains au chocolat": "Croissants en pains au chocolat",
  "Commande": "Bestelling",
  "Délai de commande": "Besteldeadline",
  "Avant 18h la veille pour le lendemain": "Voor 18u de dag ervoor",
  "Retrait": "Afhalen",
  "Directement au bar/snack du camping le matin": "Rechtstreeks bij de campingbar/'s ochtends",
  "Au bar/snack du camping": "Bij de campingbar/snackbar",
  "Notre bar": "Onze bar",
  "Juillet et août": "Juli en augustus",
  "À la carte": "À la carte",
  "Sans réservation, sauf pour les soirées à thème": "Zonder reservering, behalve voor thema-avonden",
  "Soirée moules frites — tous les vendredi": "Mosselen-friet avond — elke vrijdag",
  "Soirée paëlla — tous les dimanches": "Paella-avond — elke zondag",
  "Soirée barbecue + frites à volonté — tous les jeudis": "Barbecue + onbeperkt friet — elke donderdag",
  "À partir de 19h00": "Vanaf 19u",
  "À partir de 20h30": "Vanaf 20u30",
  "Spectacles & concerts en haute saison": "Shows & concerten in het hoogseizoen",
  "Balade équestre": "Paardrijden",
  "Pêcher dans le Haut-Bugey": "Vissen in de Haut-Bugey",
  "Escalade, accrobranche et via ferrata": "Klimmen, klauterparcours en via ferrata",
  "Partez à la découverte des paysages du Haut-Bugey : gorges, forêts, lacs et villages à explorer à pied ou à vélo !": "Ontdek de landschappen van de Haut-Bugey: kloven, bossen, meren en dorpen te verkennen te voet of per fiets!",
  "Découvrez toutes les activités disponibles près du camping pour profiter au maximum de votre séjour !": "Ontdek alle activiteiten in de buurt van de camping voor een maximaal verblijf!",
  "Tous les jours sauf le mercredi — du 15 mai au 15 septembre 2026": "Elke dag behalve woensdag — van 15 mei tot 15 september 2026",
  "Prix": "Prijzen",
  "Réservation": "Reservering",
  "Réservation obligatoire. Ne nécessite aucune préparation ni aptitude particulière.": "Reservering verplicht. Geen speciale voorbereiding nodig.",
  "Nous sommes ravis de vous inviter à un pot d'accueil le dimanche à 19h (en juillet/août). Cela sera l'occasion de faire connaissance, de vous présenter l'équipe, le planning d'animation et les informations touristiques de la région.": "We nodigen u graag uit voor een welkomstborrel op zondag om 19u (juli/augustus). Een gelegenheid om kennis te maken, het team voor te stellen, het animatieprogramma te bespreken en toeristische tips te geven."
});
